//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackbirdSql.Sys.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AttributeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AttributeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackbirdSql.Sys.Properties.AttributeResources", typeof(AttributeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string PropertyCategoryAdvanced {
            get {
                return ResourceManager.GetString("PropertyCategoryAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string PropertyCategoryConnection {
            get {
                return ResourceManager.GetString("PropertyCategoryConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string PropertyCategoryData {
            get {
                return ResourceManager.GetString("PropertyCategoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooling.
        /// </summary>
        internal static string PropertyCategoryPooling {
            get {
                return ResourceManager.GetString("PropertyCategoryPooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string PropertyCategorySecurity {
            get {
                return ResourceManager.GetString("PropertyCategorySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string PropertyCategorySource {
            get {
                return ResourceManager.GetString("PropertyCategorySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optional name of the application making the connection. This property can also be used to make equivalent connections distinctly unique..
        /// </summary>
        internal static string PropertyDescriptionApplicationName {
            get {
                return ResourceManager.GetString("PropertyDescriptionApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database character set encoding..
        /// </summary>
        internal static string PropertyDescriptionCharset {
            get {
                return ResourceManager.GetString("PropertyDescriptionCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client library for embedded databases..
        /// </summary>
        internal static string PropertyDescriptionClientLibrary {
            get {
                return ResourceManager.GetString("PropertyDescriptionClientLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout (in seconds) to wait for a command to complete execution or zero for no limit..
        /// </summary>
        internal static string PropertyDescriptionCommandTimeout {
            get {
                return ResourceManager.GetString("PropertyDescriptionCommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables or disables wire compression..
        /// </summary>
        internal static string PropertyDescriptionCompression {
            get {
                return ResourceManager.GetString("PropertyDescriptionCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time (in seconds) before unused connections in the connection pool are disposed..
        /// </summary>
        internal static string PropertyDescriptionConnectionLifeTime {
            get {
                return ResourceManager.GetString("PropertyDescriptionConnectionLifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string used to connect to the Data Source..
        /// </summary>
        internal static string PropertyDescriptionConnectionString {
            get {
                return ResourceManager.GetString("PropertyDescriptionConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout (in seconds) to wait for a connection to open..
        /// </summary>
        internal static string PropertyDescriptionConnectionTimeout {
            get {
                return ResourceManager.GetString("PropertyDescriptionConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encryption key to be used for database encryption..
        /// </summary>
        internal static string PropertyDescriptionCryptKey {
            get {
                return ResourceManager.GetString("PropertyDescriptionCryptKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local path or alias on the server to the database file..
        /// </summary>
        internal static string PropertyDescriptionDatabase {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database server name..
        /// </summary>
        internal static string PropertyDescriptionDataSource {
            get {
                return ResourceManager.GetString("PropertyDescriptionDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of cache buffers to allocate to this session..
        /// </summary>
        internal static string PropertyDescriptionDbCachePages {
            get {
                return ResourceManager.GetString("PropertyDescriptionDbCachePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database SQL dialect..
        /// </summary>
        internal static string PropertyDescriptionDialect {
            get {
                return ResourceManager.GetString("PropertyDescriptionDialect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, enlists the connections in the current transaction..
        /// </summary>
        internal static string PropertyDescriptionEnlist {
            get {
                return ResourceManager.GetString("PropertyDescriptionEnlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of rows to be fetched in a single call to read into the internal row buffer..
        /// </summary>
        internal static string PropertyDescriptionFetchSize {
            get {
                return ResourceManager.GetString("PropertyDescriptionFetchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default Isolation Level for implicit transactions..
        /// </summary>
        internal static string PropertyDescriptionIsolationLevel {
            get {
                return ResourceManager.GetString("PropertyDescriptionIsolationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of connections allowed in a pool..
        /// </summary>
        internal static string PropertyDescriptionMaxPoolSize {
            get {
                return ResourceManager.GetString("PropertyDescriptionMaxPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of connections allowed in a pool..
        /// </summary>
        internal static string PropertyDescriptionMinPoolSize {
            get {
                return ResourceManager.GetString("PropertyDescriptionMinPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables database triggers for this connection..
        /// </summary>
        internal static string PropertyDescriptionNoDatabaseTriggers {
            get {
                return ResourceManager.GetString("PropertyDescriptionNoDatabaseTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, disables a garbage collect the database upon attachment..
        /// </summary>
        internal static string PropertyDescriptionNoGarbageCollect {
            get {
                return ResourceManager.GetString("PropertyDescriptionNoGarbageCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size (in bytes) of network packets. The Packet Size can be in the range of 512 - 32767 bytes..
        /// </summary>
        internal static string PropertyDescriptionPacketSize {
            get {
                return ResourceManager.GetString("PropertyDescriptionPacketSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of parallel workers that can be allocated for database operations..
        /// </summary>
        internal static string PropertyDescriptionParallelWorkers {
            get {
                return ResourceManager.GetString("PropertyDescriptionParallelWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database user login password..
        /// </summary>
        internal static string PropertyDescriptionPassword {
            get {
                return ResourceManager.GetString("PropertyDescriptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true then identical connections will use a common connection from the appropriate pool..
        /// </summary>
        internal static string PropertyDescriptionPooling {
            get {
                return ResourceManager.GetString("PropertyDescriptionPooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TCP/IP port for server connections..
        /// </summary>
        internal static string PropertyDescriptionPort {
            get {
                return ResourceManager.GetString("PropertyDescriptionPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the number of rows affected in the result set if set to true..
        /// </summary>
        internal static string PropertyDescriptionReturnRecordsAffected {
            get {
                return ResourceManager.GetString("PropertyDescriptionReturnRecordsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user role..
        /// </summary>
        internal static string PropertyDescriptionRole {
            get {
                return ResourceManager.GetString("PropertyDescriptionRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The physical server type..
        /// </summary>
        internal static string PropertyDescriptionServerType {
            get {
                return ResourceManager.GetString("PropertyDescriptionServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database user login ID..
        /// </summary>
        internal static string PropertyDescriptionUserID {
            get {
                return ResourceManager.GetString("PropertyDescriptionUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wire encryption method..
        /// </summary>
        internal static string PropertyDescriptionWireCrypt {
            get {
                return ResourceManager.GetString("PropertyDescriptionWireCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        internal static string PropertyDisplayApplicationName {
            get {
                return ResourceManager.GetString("PropertyDisplayApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Set.
        /// </summary>
        internal static string PropertyDisplayCharset {
            get {
                return ResourceManager.GetString("PropertyDisplayCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Library.
        /// </summary>
        internal static string PropertyDisplayClientLibrary {
            get {
                return ResourceManager.GetString("PropertyDisplayClientLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Timeout.
        /// </summary>
        internal static string PropertyDisplayCommandTimeout {
            get {
                return ResourceManager.GetString("PropertyDisplayCommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        internal static string PropertyDisplayCompression {
            get {
                return ResourceManager.GetString("PropertyDisplayCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Lifetime.
        /// </summary>
        internal static string PropertyDisplayConnectionLifeTime {
            get {
                return ResourceManager.GetString("PropertyDisplayConnectionLifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        internal static string PropertyDisplayConnectionString {
            get {
                return ResourceManager.GetString("PropertyDisplayConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Timeout.
        /// </summary>
        internal static string PropertyDisplayConnectionTimeout {
            get {
                return ResourceManager.GetString("PropertyDisplayConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypt Key.
        /// </summary>
        internal static string PropertyDisplayCryptKey {
            get {
                return ResourceManager.GetString("PropertyDisplayCryptKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string PropertyDisplayDatabase {
            get {
                return ResourceManager.GetString("PropertyDisplayDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource.
        /// </summary>
        internal static string PropertyDisplayDataSource {
            get {
                return ResourceManager.GetString("PropertyDisplayDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Pages.
        /// </summary>
        internal static string PropertyDisplayDbCachePages {
            get {
                return ResourceManager.GetString("PropertyDisplayDbCachePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialect.
        /// </summary>
        internal static string PropertyDisplayDialect {
            get {
                return ResourceManager.GetString("PropertyDisplayDialect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlist.
        /// </summary>
        internal static string PropertyDisplayEnlist {
            get {
                return ResourceManager.GetString("PropertyDisplayEnlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Size.
        /// </summary>
        internal static string PropertyDisplayFetchSize {
            get {
                return ResourceManager.GetString("PropertyDisplayFetchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolation Level.
        /// </summary>
        internal static string PropertyDisplayIsolationLevel {
            get {
                return ResourceManager.GetString("PropertyDisplayIsolationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Pool Size.
        /// </summary>
        internal static string PropertyDisplayMaxPoolSize {
            get {
                return ResourceManager.GetString("PropertyDisplayMaxPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Pool Size.
        /// </summary>
        internal static string PropertyDisplayMinPoolSize {
            get {
                return ResourceManager.GetString("PropertyDisplayMinPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Triggers.
        /// </summary>
        internal static string PropertyDisplayNoDatabaseTriggers {
            get {
                return ResourceManager.GetString("PropertyDisplayNoDatabaseTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Garbage Collect.
        /// </summary>
        internal static string PropertyDisplayNoGarbageCollect {
            get {
                return ResourceManager.GetString("PropertyDisplayNoGarbageCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Size.
        /// </summary>
        internal static string PropertyDisplayPacketSize {
            get {
                return ResourceManager.GetString("PropertyDisplayPacketSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Workers.
        /// </summary>
        internal static string PropertyDisplayParallelWorkers {
            get {
                return ResourceManager.GetString("PropertyDisplayParallelWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PropertyDisplayPassword {
            get {
                return ResourceManager.GetString("PropertyDisplayPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooling.
        /// </summary>
        internal static string PropertyDisplayPooling {
            get {
                return ResourceManager.GetString("PropertyDisplayPooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string PropertyDisplayPort {
            get {
                return ResourceManager.GetString("PropertyDisplayPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Records Affected.
        /// </summary>
        internal static string PropertyDisplayReturnRecordsAffected {
            get {
                return ResourceManager.GetString("PropertyDisplayReturnRecordsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string PropertyDisplayRole {
            get {
                return ResourceManager.GetString("PropertyDisplayRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Type.
        /// </summary>
        internal static string PropertyDisplayServerType {
            get {
                return ResourceManager.GetString("PropertyDisplayServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string PropertyDisplayUserID {
            get {
                return ResourceManager.GetString("PropertyDisplayUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire Crypt.
        /// </summary>
        internal static string PropertyDisplayWireCrypt {
            get {
                return ResourceManager.GetString("PropertyDisplayWireCrypt", resourceCulture);
            }
        }
    }
}
