//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackbirdSql.Sys.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackbirdSql.Sys.Properties.ControlsResources", typeof(ControlsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional data.
        /// </summary>
        internal static string AdvancedInformationDialog_AdditionalData {
            get {
                return ResourceManager.GetString("AdvancedInformationDialog_AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All messages.
        /// </summary>
        internal static string AdvancedInformationDialog_AllMessages {
            get {
                return ResourceManager.GetString("AdvancedInformationDialog_AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help link.
        /// </summary>
        internal static string AdvancedInformationDialog_HelpLink {
            get {
                return ResourceManager.GetString("AdvancedInformationDialog_HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string AdvancedInformationDialog_Message {
            get {
                return ResourceManager.GetString("AdvancedInformationDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Info.
        /// </summary>
        internal static string AdvancedInformationDialog_NodeExceptionInfo {
            get {
                return ResourceManager.GetString("AdvancedInformationDialog_NodeExceptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string AdvancedMessageBox_AbortButton {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_AbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}....
        /// </summary>
        internal static string AdvancedMessageBox_AddEllipsis {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_AddEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDITIONAL INFORMATION:.
        /// </summary>
        internal static string AdvancedMessageBox_AdditionalInfo {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUTTONS:.
        /// </summary>
        internal static string AdvancedMessageBox_Buttons {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AdvancedMessageBox_CancelButton {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be completed..
        /// </summary>
        internal static string AdvancedMessageBox_CantComplete {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_CantComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Show method can be called only once on an ExceptionMessageBox object. To display a new message, you must create a new instance of the ExceptionMessageBox class..
        /// </summary>
        internal static string AdvancedMessageBox_CantReuseObject {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_CantReuseObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical details cannot be displayed..
        /// </summary>
        internal static string AdvancedMessageBox_CantShowTechnicalDetailsError {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_CantShowTechnicalDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the following help link: {0}..
        /// </summary>
        internal static string AdvancedMessageBox_CantStartHelpLink {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_CantStartHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For help, click: {0}.
        /// </summary>
        internal static string AdvancedMessageBox_ClipboardOrEmailHelpLink {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_ClipboardOrEmailHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Location:.
        /// </summary>
        internal static string AdvancedMessageBox_CodeLocation {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_CodeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message cannot be copied to the clipboard..
        /// </summary>
        internal static string AdvancedMessageBox_CopyToClipboardError {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_CopyToClipboardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;o not show this message again.
        /// </summary>
        internal static string AdvancedMessageBox_DefaultCheckboxText {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_DefaultCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Error: {0}).
        /// </summary>
        internal static string AdvancedMessageBox_ErrorNumber {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string AdvancedMessageBox_ErrorSource {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_ErrorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}, Error: {1}).
        /// </summary>
        internal static string AdvancedMessageBox_ErrorSourceNumber {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_ErrorSourceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Help For: &quot;{0}&quot;.
        /// </summary>
        internal static string AdvancedMessageBox_HelpMenuText {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_HelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE: .
        /// </summary>
        internal static string AdvancedMessageBox_MessageTitle {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Help Available For: &quot;{0}&quot;.
        /// </summary>
        internal static string AdvancedMessageBox_NoHelpMenuText {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_NoHelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Number: {0}.
        /// </summary>
        internal static string AdvancedMessageBox_SqlError {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_SqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number: {0}.
        /// </summary>
        internal static string AdvancedMessageBox_SqlLineNumber {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_SqlLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure: {0}.
        /// </summary>
        internal static string AdvancedMessageBox_SqlProcedure {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_SqlProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Information.
        /// </summary>
        internal static string AdvancedMessageBox_SqlServerInfo {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_SqlServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name: {0}.
        /// </summary>
        internal static string AdvancedMessageBox_SqlServerName {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_SqlServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity: {0}.
        /// </summary>
        internal static string AdvancedMessageBox_SqlSeverity {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_SqlSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State: {0}.
        /// </summary>
        internal static string AdvancedMessageBox_SqlState {
            get {
                return ResourceManager.GetString("AdvancedMessageBox_SqlState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Server.
        /// </summary>
        internal static string MessageCtl_ConnectToServer {
            get {
                return ResourceManager.GetString("MessageCtl_ConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify text for the button when Buttons = NewMessageBoxButtons.Custom..
        /// </summary>
        internal static string MessageCtl_CustomButtonTextError {
            get {
                return ResourceManager.GetString("MessageCtl_CustomButtonTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fail.
        /// </summary>
        internal static string MessageCtl_FailButton {
            get {
                return ResourceManager.GetString("MessageCtl_FailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        internal static string MessageCtl_IgnoreButton {
            get {
                return ResourceManager.GetString("MessageCtl_IgnoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageLevelCount must be greater than 0..
        /// </summary>
        internal static string MessageCtl_MessageLevelCountError {
            get {
                return ResourceManager.GetString("MessageCtl_MessageLevelCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string MessageCtl_NoButton {
            get {
                return ResourceManager.GetString("MessageCtl_NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MessageCtl_OKButton {
            get {
                return ResourceManager.GetString("MessageCtl_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string MessageCtl_RetryButton {
            get {
                return ResourceManager.GetString("MessageCtl_RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string MessageCtl_YesButton {
            get {
                return ResourceManager.GetString("MessageCtl_YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message ID.
        /// </summary>
        internal static string PrivacyConfirmationDialog_MessageId {
            get {
                return ResourceManager.GetString("PrivacyConfirmationDialog_MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Source.
        /// </summary>
        internal static string PrivacyConfirmationDialog_MessageSource {
            get {
                return ResourceManager.GetString("PrivacyConfirmationDialog_MessageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string PrivacyConfirmationDialog_PrivacyItemName {
            get {
                return ResourceManager.GetString("PrivacyConfirmationDialog_PrivacyItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string PrivacyConfirmationDialog_PrivacyItemValue {
            get {
                return ResourceManager.GetString("PrivacyConfirmationDialog_PrivacyItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string PrivacyConfirmationDialog_ProductName {
            get {
                return ResourceManager.GetString("PrivacyConfirmationDialog_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Version.
        /// </summary>
        internal static string PrivacyConfirmationDialog_ProductVersion {
            get {
                return ResourceManager.GetString("PrivacyConfirmationDialog_ProductVersion", resourceCulture);
            }
        }
    }
}
