//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackbirdSql.Common.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackbirdSql.Common.Exceptions.ExceptionsResources", typeof(ExceptionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        public static string AbortButton {
            get {
                return ResourceManager.GetString("AbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}....
        /// </summary>
        public static string AddEllipsis {
            get {
                return ResourceManager.GetString("AddEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDITIONAL INFORMATION:.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All messages.
        /// </summary>
        public static string AdvInfoAllMessages {
            get {
                return ResourceManager.GetString("AdvInfoAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional data.
        /// </summary>
        public static string ADvInfoData {
            get {
                return ResourceManager.GetString("ADvInfoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help link.
        /// </summary>
        public static string AdvInfoHelpLink {
            get {
                return ResourceManager.GetString("AdvInfoHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string AdvInfoMessage {
            get {
                return ResourceManager.GetString("AdvInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUTTONS:.
        /// </summary>
        public static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be completed..
        /// </summary>
        public static string CantComplete {
            get {
                return ResourceManager.GetString("CantComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Show method can be called only once on an ExceptionMessageBox object. To display a new message, you must create a new instance of the ExceptionMessageBox class..
        /// </summary>
        public static string CantReuseObject {
            get {
                return ResourceManager.GetString("CantReuseObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical details cannot be displayed..
        /// </summary>
        public static string CantShowTechnicalDetailsError {
            get {
                return ResourceManager.GetString("CantShowTechnicalDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the following help link: {0}..
        /// </summary>
        public static string CantStartHelpLink {
            get {
                return ResourceManager.GetString("CantStartHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For help, click: {0}.
        /// </summary>
        public static string ClipboardOrEmailHelpLink {
            get {
                return ResourceManager.GetString("ClipboardOrEmailHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Location:.
        /// </summary>
        public static string CodeLocation {
            get {
                return ResourceManager.GetString("CodeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message cannot be copied to the clipboard..
        /// </summary>
        public static string CopyToClipboardError {
            get {
                return ResourceManager.GetString("CopyToClipboardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify text for the button when Buttons = NewMessageBoxButtons.Custom..
        /// </summary>
        public static string CustomButtonTextError {
            get {
                return ResourceManager.GetString("CustomButtonTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;o not show this message again.
        /// </summary>
        public static string DefaultCheckboxText {
            get {
                return ResourceManager.GetString("DefaultCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Error: {0}).
        /// </summary>
        public static string ErrorNumber {
            get {
                return ResourceManager.GetString("ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        public static string ErrorSource {
            get {
                return ResourceManager.GetString("ErrorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        public static string ErrorSource1 {
            get {
                return ResourceManager.GetString("ErrorSource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}, Error: {1}).
        /// </summary>
        public static string ErrorSourceNumber {
            get {
                return ResourceManager.GetString("ErrorSourceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}, Error: {1}).
        /// </summary>
        public static string ErrorSourceNumber1 {
            get {
                return ResourceManager.GetString("ErrorSourceNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fail.
        /// </summary>
        public static string FailButton {
            get {
                return ResourceManager.GetString("FailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Help For: &quot;{0}&quot;.
        /// </summary>
        public static string HelpMenuText {
            get {
                return ResourceManager.GetString("HelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        public static string IgnoreButton {
            get {
                return ResourceManager.GetString("IgnoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message ID.
        /// </summary>
        public static string MessageID {
            get {
                return ResourceManager.GetString("MessageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageLevelCount must be greater than 0..
        /// </summary>
        public static string MessageLevelCountError {
            get {
                return ResourceManager.GetString("MessageLevelCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Source.
        /// </summary>
        public static string MessageSource {
            get {
                return ResourceManager.GetString("MessageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE: .
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        public static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Help Available For: &quot;{0}&quot;.
        /// </summary>
        public static string NoHelpMenuText {
            get {
                return ResourceManager.GetString("NoHelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string PrivacyItemName {
            get {
                return ResourceManager.GetString("PrivacyItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PrivacyItemValue {
            get {
                return ResourceManager.GetString("PrivacyItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Version.
        /// </summary>
        public static string ProductVersion {
            get {
                return ResourceManager.GetString("ProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        public static string RetryButton {
            get {
                return ResourceManager.GetString("RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientConnectionId:{0}.
        /// </summary>
        public static string SQL_ExClientConnectionId {
            get {
                return ResourceManager.GetString("SQL_ExClientConnectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Number:{0},State:{1},Class:{2}.
        /// </summary>
        public static string SQL_ExErrorNumberStateClass {
            get {
                return ResourceManager.GetString("SQL_ExErrorNumberStateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientConnectionId before routing:{0}.
        /// </summary>
        public static string SQL_ExOriginalClientConnectionId {
            get {
                return ResourceManager.GetString("SQL_ExOriginalClientConnectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Destination:{0}.
        /// </summary>
        public static string SQL_ExRoutingDestination {
            get {
                return ResourceManager.GetString("SQL_ExRoutingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Number: {0}.
        /// </summary>
        public static string SqlError {
            get {
                return ResourceManager.GetString("SqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number: {0}.
        /// </summary>
        public static string SqlLineNumber {
            get {
                return ResourceManager.GetString("SqlLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure: {0}.
        /// </summary>
        public static string SqlProcedure {
            get {
                return ResourceManager.GetString("SqlProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Information.
        /// </summary>
        public static string SqlServerInfo {
            get {
                return ResourceManager.GetString("SqlServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name: {0}.
        /// </summary>
        public static string SqlServerName {
            get {
                return ResourceManager.GetString("SqlServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server.
        /// </summary>
        public static string SqlServerSource {
            get {
                return ResourceManager.GetString("SqlServerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity: {0}.
        /// </summary>
        public static string SqlSeverity {
            get {
                return ResourceManager.GetString("SqlSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State: {0}.
        /// </summary>
        public static string SqlState {
            get {
                return ResourceManager.GetString("SqlState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
