FOR /d /r . %%d IN ("BlackbirdSql.Controller\bin") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.Controller\obj") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.Core\bin") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.Core\obj") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.Data\bin") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.Data\obj") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.EditorExtension\bin") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.EditorExtension\obj") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.LanguageExtension\bin") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.LanguageExtension\obj") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.Shared\bin") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.Shared\obj") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.Sys\bin") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.Sys\obj") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.VisualStudio.Ddex\bin") DO @IF EXIST "%%d" rd /s /q "%%d"
FOR /d /r . %%d IN ("BlackbirdSql.VisualStudio.Ddex\obj") DO @IF EXIST "%%d" rd /s /q "%%d"
rd /s /q "packages"