//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackbirdSql.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackbirdSql.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument string is missing a closing double quote..
        /// </summary>
        public static string ArgumentParsing_DoubleQuoteMissingError {
            get {
                return ResourceManager.GetString("ArgumentParsing_DoubleQuoteMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class: {0} Number: {1} .
        /// </summary>
        public static string ClassNumber {
            get {
                return ResourceManager.GetString("ClassNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Alter Function Source.
        /// </summary>
        public static string CommandProvider_AlterFunctionScript {
            get {
                return ResourceManager.GetString("CommandProvider_AlterFunctionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Alter Procedure Source.
        /// </summary>
        public static string CommandProvider_AlterStoredProcedureScript {
            get {
                return ResourceManager.GetString("CommandProvider_AlterStoredProcedureScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Alter Trigger Expression.
        /// </summary>
        public static string CommandProvider_AlterTriggerScript {
            get {
                return ResourceManager.GetString("CommandProvider_AlterTriggerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Alter View Definition.
        /// </summary>
        public static string CommandProvider_AlterViewScript {
            get {
                return ResourceManager.GetString("CommandProvider_AlterViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlViewTextObjectCommandProvider_CancelExecution.
        /// </summary>
        public static string CommandProvider_CancelExecution {
            get {
                return ResourceManager.GetString("CommandProvider_CancelExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Create Procedure Source.
        /// </summary>
        public static string CommandProvider_CreateStoredProcedureScript {
            get {
                return ResourceManager.GetString("CommandProvider_CreateStoredProcedureScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Create View Definition.
        /// </summary>
        public static string CommandProvider_CreateViewScript {
            get {
                return ResourceManager.GetString("CommandProvider_CreateViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Connection.
        /// </summary>
        public static string CommandProvider_DeleteDatabaseConnection {
            get {
                return ResourceManager.GetString("CommandProvider_DeleteDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename Connection.
        /// </summary>
        public static string CommandProvider_EditDatabaseLabel {
            get {
                return ResourceManager.GetString("CommandProvider_EditDatabaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Designer Query.
        /// </summary>
        public static string CommandProvider_NewGlobalDesigner {
            get {
                return ResourceManager.GetString("CommandProvider_NewGlobalDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SQL &amp;Query.
        /// </summary>
        public static string CommandProvider_NewQuery {
            get {
                return ResourceManager.GetString("CommandProvider_NewQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New System Designer Query.
        /// </summary>
        public static string CommandProvider_NewSystemDesigner {
            get {
                return ResourceManager.GetString("CommandProvider_NewSystemDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New User Designer Query.
        /// </summary>
        public static string CommandProvider_NewUserDesigner {
            get {
                return ResourceManager.GetString("CommandProvider_NewUserDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source available.
        /// </summary>
        public static string CommandProvider_NoSourceAvailable {
            get {
                return ResourceManager.GetString("CommandProvider_NoSourceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Column Expression.
        /// </summary>
        public static string CommandProvider_OpenColumnScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenColumnScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Foreign Key Expression.
        /// </summary>
        public static string CommandProvider_OpenForeignKeyScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenForeignKeyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Create Function Source.
        /// </summary>
        public static string CommandProvider_OpenFunctionScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenFunctionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Index Expression.
        /// </summary>
        public static string CommandProvider_OpenIndexScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenIndexScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Script.
        /// </summary>
        public static string CommandProvider_OpenScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Execute Procedure Script.
        /// </summary>
        public static string CommandProvider_OpenStoredProcedureScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenStoredProcedureScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open System Script.
        /// </summary>
        public static string CommandProvider_OpenSystemScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenSystemScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Table SQL Query.
        /// </summary>
        public static string CommandProvider_OpenTableScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenTableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Create Trigger Expression.
        /// </summary>
        public static string CommandProvider_OpenTriggerScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenTriggerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open User Script.
        /// </summary>
        public static string CommandProvider_OpenUserScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenUserScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open View Query.
        /// </summary>
        public static string CommandProvider_OpenViewScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document moniker path name is too long.
        /// </summary>
        public static string CommandProvider_PathTooLong {
            get {
                return ResourceManager.GetString("CommandProvider_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlViewTextObjectCommandProvider_PromptSaveObject.
        /// </summary>
        public static string CommandProvider_PromptSaveObject {
            get {
                return ResourceManager.GetString("CommandProvider_PromptSaveObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Table in &amp;Designer.
        /// </summary>
        public static string CommandProvider_RetrieveTableDesignerData {
            get {
                return ResourceManager.GetString("CommandProvider_RetrieveTableDesignerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open View in &amp;Designer.
        /// </summary>
        public static string CommandProvider_RetrieveViewDesignerData {
            get {
                return ResourceManager.GetString("CommandProvider_RetrieveViewDesignerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Solution Config.
        /// </summary>
        public static string CommandProvider_ValidateGlobalSolution {
            get {
                return ResourceManager.GetString("CommandProvider_ValidateGlobalSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProviderFactory recovery -&gt; Validating {0} factories....
        /// </summary>
        public static string DbProviderFactoriesEx_Recovery {
            get {
                return ResourceManager.GetString("DbProviderFactoriesEx_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProviderFactory recovery -&gt; Invariant &apos;{0}&apos; recovered using ConfigurationManager removal after registration failure..
        /// </summary>
        public static string DbProviderFactoriesEx_RecoveryConfigurationManagerConfigurationManager {
            get {
                return ResourceManager.GetString("DbProviderFactoriesEx_RecoveryConfigurationManagerConfigurationManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProviderFactory recovery -&gt; Invariant &apos;{0}&apos; recovered using ConfigurationManager removal after load error..
        /// </summary>
        public static string DbProviderFactoriesEx_RecoveryConfigurationManagerInvalidated {
            get {
                return ResourceManager.GetString("DbProviderFactoriesEx_RecoveryConfigurationManagerInvalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProviderFactory recovery -&gt; Invariant &apos;{0}&apos; recovered using direct removal after registration failure..
        /// </summary>
        public static string DbProviderFactoriesEx_RecoveryDirectConfigurationManager {
            get {
                return ResourceManager.GetString("DbProviderFactoriesEx_RecoveryDirectConfigurationManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProviderFactory recovery -&gt; Invariant &apos;{0}&apos; recovered using direct removal after load error..
        /// </summary>
        public static string DbProviderFactoriesEx_RecoveryDirectInvalidated {
            get {
                return ResourceManager.GetString("DbProviderFactoriesEx_RecoveryDirectInvalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProviderFactory recovery -&gt; Invariant &apos;{0}&apos; error. Timed out waiting for factory to appear..
        /// </summary>
        public static string DbProviderFactoriesEx_RecoveryInvariantFailed {
            get {
                return ResourceManager.GetString("DbProviderFactoriesEx_RecoveryInvariantFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProviderFactory recovery -&gt; Invariant &apos;{0}&apos; has faulted. Attempting recovery....
        /// </summary>
        public static string DbProviderFactoriesEx_RecoveryInvariantFaulted {
            get {
                return ResourceManager.GetString("DbProviderFactoriesEx_RecoveryInvariantFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProviderFactory recovery completed: Found {0} faulted invariants, {1} recovered. Total recovery time was {2}ms..
        /// </summary>
        public static string DbProviderFactoriesEx_RecoveryResult {
            get {
                return ResourceManager.GetString("DbProviderFactoriesEx_RecoveryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate icon for Server Engine Type {0}..
        /// </summary>
        public static string EngineTypeIconNotfound {
            get {
                return ResourceManager.GetString("EngineTypeIconNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ErmBindingSource_Reset {
            get {
                return ResourceManager.GetString("ErmBindingSource_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add a null connection.
        /// </summary>
        public static string ExceptionAttemptToAddNullConnection {
            get {
                return ResourceManager.GetString("ExceptionAttemptToAddNullConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginTransaction failed. Transaction already exists..
        /// </summary>
        public static string ExceptionBeginTransactionAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionBeginTransactionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginTransaction failed. Connection is null or not open..
        /// </summary>
        public static string ExceptionBeginTransactionConnectionUnavailable {
            get {
                return ResourceManager.GetString("ExceptionBeginTransactionConnectionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot store null in settings store. SettingsModel&lt;{0}&gt;. CollectionName:{1} PropertyName:{2} dataType:{3} PropertyType:{4} Value:{5}.
        /// </summary>
        public static string ExceptionCannotStoreNullInSettingsStore {
            get {
                return ResourceManager.GetString("ExceptionCannotStoreNullInSettingsStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection closed.
        /// </summary>
        public static string ExceptionConnectionClosed {
            get {
                return ResourceManager.GetString("ExceptionConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection disposed.
        /// </summary>
        public static string ExceptionConnectionDisposed {
            get {
                return ResourceManager.GetString("ExceptionConnectionDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionKey for explorer connection {0} for node {1} is null.
        /// </summary>
        public static string ExceptionConnectionKeyNull {
            get {
                return ResourceManager.GetString("ExceptionConnectionKeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is null.
        /// </summary>
        public static string ExceptionConnectionNull {
            get {
                return ResourceManager.GetString("ExceptionConnectionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create batch execution object: {0}..
        /// </summary>
        public static string ExceptionCreateBatchExecutionObject {
            get {
                return ResourceManager.GetString("ExceptionCreateBatchExecutionObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must create Rdt Manager on the UI Thread.
        /// </summary>
        public static string ExceptionCreateRdtManagerOnUiThread {
            get {
                return ResourceManager.GetString("ExceptionCreateRdtManagerOnUiThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType {0} is not capable of supporting native storage type {1}.
        /// </summary>
        public static string ExceptionDataTypeStorageTypeNotSupported {
            get {
                return ResourceManager.GetString("ExceptionDataTypeStorageTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Manager is still trying to keep doc data alive on dispose, this could be a symptom of memory leak from invisible doc data..
        /// </summary>
        public static string ExceptionDocDataKeepAlive {
            get {
                return ResourceManager.GetString("ExceptionDocDataKeepAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events already enabled..
        /// </summary>
        public static string ExceptionEventsAlreadyEnabled {
            get {
                return ResourceManager.GetString("ExceptionEventsAlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file: {0}.
        /// </summary>
        public static string ExceptionFailedToSaveFile {
            get {
                return ResourceManager.GetString("ExceptionFailedToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get method &apos;{0}&apos; for property {1}.
        /// </summary>
        public static string ExceptionGetMethodForPropertyFailed {
            get {
                return ResourceManager.GetString("ExceptionGetMethodForPropertyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCommand() GlobalNewQuery returned null.
        /// </summary>
        public static string ExceptionGlobalNewQueryCommandNotFound {
            get {
                return ResourceManager.GetString("ExceptionGlobalNewQueryCommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} method of SettingsModel {1} for property {2} returned a null value..
        /// </summary>
        public static string ExceptionMethodPropertyReturnedNull {
            get {
                return ResourceManager.GetString("ExceptionMethodPropertyReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UriComponents.SerializationInfoString must not be combined with other UriComponents..
        /// </summary>
        public static string ExceptionNetUriNotJustSerialization {
            get {
                return ResourceManager.GetString("ExceptionNetUriNotJustSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCommand() NewQueryGlobal returned null.
        /// </summary>
        public static string ExceptionNewQueryGlobalCommandNotFound {
            get {
                return ResourceManager.GetString("ExceptionNewQueryGlobalCommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get next tree child item returned null..
        /// </summary>
        public static string ExceptionNextTreeChildItemNull {
            get {
                return ResourceManager.GetString("ExceptionNextTreeChildItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get next tree item from caret returned null..
        /// </summary>
        public static string ExceptionNextTreeItemFromCaretNull {
            get {
                return ResourceManager.GetString("ExceptionNextTreeItemFromCaretNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get next tree item from root returned null..
        /// </summary>
        public static string ExceptionNextTreeItemFromRootNull {
            get {
                return ResourceManager.GetString("ExceptionNextTreeItemFromRootNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate Describer for connection parameter &apos;{0}&apos;..
        /// </summary>
        public static string ExceptionParameterDescriberNotFound {
            get {
                return ResourceManager.GetString("ExceptionParameterDescriberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving node {0} property: {1}.
        /// </summary>
        public static string ExceptionRetrievingNodeProperty {
            get {
                return ResourceManager.GetString("ExceptionRetrievingNodeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Load failed for Settings Model {0}. CollectionName:{1} PropertyName:{2} dataType:{3} PropertyType:{4} Value:{5}.
        /// </summary>
        public static string ExceptionSettingsModelLoadDefaultFailed {
            get {
                return ResourceManager.GetString("ExceptionSettingsModelLoadDefaultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed for Settings Model {0}. PropertyName:{1} dataType:{2} PropertyType:{3} Value:{4}.
        /// </summary>
        public static string ExceptionSettingsModelLoadFailed {
            get {
                return ResourceManager.GetString("ExceptionSettingsModelLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed for Settings Model {0}. CollectionName:{1} PropertyName:{2} dataType:{3} PropertyType:{4} Value:{5}.
        /// </summary>
        public static string ExceptionSettingsModelSaveFailed {
            get {
                return ResourceManager.GetString("ExceptionSettingsModelSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find window &apos;SHBrowseForFolder ShellNameSpace Control&apos;..
        /// </summary>
        public static string ExceptionSHBrowseForFolderNotFound {
            get {
                return ResourceManager.GetString("ExceptionSHBrowseForFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find window &apos;SysTreeView32&apos;..
        /// </summary>
        public static string ExceptionSysTreeView32NotFound {
            get {
                return ResourceManager.GetString("ExceptionSysTreeView32NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Error at Column index: {0}..
        /// </summary>
        public static string ExceptionTriggerErrorAtColumnIndex {
            get {
                return ResourceManager.GetString("ExceptionTriggerErrorAtColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at Trigger column index: {0}, Generator column index: {1}..
        /// </summary>
        public static string ExceptionTriggerGeneratorErrorAtColumnIndex {
            get {
                return ResourceManager.GetString("ExceptionTriggerGeneratorErrorAtColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry number {0}. Ignoring Exception: {1}.
        /// </summary>
        public static string IgnoreOnException {
            get {
                return ResourceManager.GetString("IgnoreOnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database path: {0}..
        /// </summary>
        public static string LabelDatabasePath {
            get {
                return ResourceManager.GetString("LabelDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame file: {0}, Moniker: {1}..
        /// </summary>
        public static string LabelFrameFileAndMoniker {
            get {
                return ResourceManager.GetString("LabelFrameFileAndMoniker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension load statistics:
        ///      Async initialization: {0}ms, MainThread initializations: {1}ms
        ///      SwitchToMainThread: {2}ms
        ///      Total time (excl. SwitchToMainThread): {3}ms.
        ///.
        /// </summary>
        public static string LoadTimeStatistics {
            get {
                return ResourceManager.GetString("LoadTimeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewQuery.
        /// </summary>
        public static string NewQueryBaseName {
            get {
                return ResourceManager.GetString("NewQueryBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The properties are not extensible..
        /// </summary>
        public static string Properties_NotExtensible {
            get {
                return ResourceManager.GetString("Properties_NotExtensible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}.
        /// </summary>
        public static string RctEdmDatasetFormat {
            get {
                return ResourceManager.GetString("RctEdmDatasetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  {1}.
        /// </summary>
        public static string RctGlyphFormat {
            get {
                return ResourceManager.GetString("RctGlyphFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}   {1}.
        /// </summary>
        public static string RctGlyphFormat2 {
            get {
                return ResourceManager.GetString("RctGlyphFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}.
        /// </summary>
        public static string RctProjectDatasetNameFormat {
            get {
                return ResourceManager.GetString("RctProjectDatasetNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string RctUtilityDatasetNameFormat {
            get {
                return ResourceManager.GetString("RctUtilityDatasetNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove failed. Property {0} does not exist..
        /// </summary>
        public static string Remove_Failed_Property_NotFound {
            get {
                return ResourceManager.GetString("Remove_Failed_Property_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found: {0}.
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry number {0}. Delaying {1} ms before next retry. Exception: {2}.
        /// </summary>
        public static string RetryOnException {
            get {
                return ResourceManager.GetString("RetryOnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty.
        /// </summary>
        public static string TextBoxRequiredFieldToolTip {
            get {
                return ResourceManager.GetString("TextBoxRequiredFieldToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED to find window frame for mkDocument: {0}.
        /// </summary>
        public static string WarningWindowFrameForDocumentNotFound {
            get {
                return ResourceManager.GetString("WarningWindowFrameForDocumentNotFound", resourceCulture);
            }
        }
    }
}
