//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackbirdSql.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackbirdSql.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument string is missing a closing double quote..
        /// </summary>
        public static string ArgumentParsing_DoubleQuoteMissingError {
            get {
                return ResourceManager.GetString("ArgumentParsing_DoubleQuoteMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class: {0} Number: {1} .
        /// </summary>
        public static string ClassNumber {
            get {
                return ResourceManager.GetString("ClassNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Alter Function Source.
        /// </summary>
        public static string CommandProvider_AlterFunctionScript {
            get {
                return ResourceManager.GetString("CommandProvider_AlterFunctionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Alter Procedure Source.
        /// </summary>
        public static string CommandProvider_AlterStoredProcedureScript {
            get {
                return ResourceManager.GetString("CommandProvider_AlterStoredProcedureScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Alter Trigger Expression.
        /// </summary>
        public static string CommandProvider_AlterTriggerScript {
            get {
                return ResourceManager.GetString("CommandProvider_AlterTriggerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Alter View Definition.
        /// </summary>
        public static string CommandProvider_AlterViewScript {
            get {
                return ResourceManager.GetString("CommandProvider_AlterViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlViewTextObjectCommandProvider_CancelExecution.
        /// </summary>
        public static string CommandProvider_CancelExecution {
            get {
                return ResourceManager.GetString("CommandProvider_CancelExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Global Query.
        /// </summary>
        public static string CommandProvider_NewQuery {
            get {
                return ResourceManager.GetString("CommandProvider_NewQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New System Query.
        /// </summary>
        public static string CommandProvider_NewSystemQuery {
            get {
                return ResourceManager.GetString("CommandProvider_NewSystemQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New User Query.
        /// </summary>
        public static string CommandProvider_NewUserQuery {
            get {
                return ResourceManager.GetString("CommandProvider_NewUserQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source available.
        /// </summary>
        public static string CommandProvider_NoSourceAvailable {
            get {
                return ResourceManager.GetString("CommandProvider_NoSourceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Column Expression.
        /// </summary>
        public static string CommandProvider_OpenColumnScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenColumnScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Foreign Key Expression.
        /// </summary>
        public static string CommandProvider_OpenForeignKeyScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenForeignKeyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Create Function Source.
        /// </summary>
        public static string CommandProvider_OpenFunctionScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenFunctionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Index Expression.
        /// </summary>
        public static string CommandProvider_OpenIndexScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenIndexScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Script.
        /// </summary>
        public static string CommandProvider_OpenScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Executable Procedure Source.
        /// </summary>
        public static string CommandProvider_OpenStoredProcedureScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenStoredProcedureScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open System Script.
        /// </summary>
        public static string CommandProvider_OpenSystemScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenSystemScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Create Trigger Expression.
        /// </summary>
        public static string CommandProvider_OpenTriggerScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenTriggerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open User Script.
        /// </summary>
        public static string CommandProvider_OpenUserScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenUserScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open View Definition.
        /// </summary>
        public static string CommandProvider_OpenViewScript {
            get {
                return ResourceManager.GetString("CommandProvider_OpenViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document moniker path name is too long.
        /// </summary>
        public static string CommandProvider_PathTooLong {
            get {
                return ResourceManager.GetString("CommandProvider_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlViewTextObjectCommandProvider_PromptSaveObject.
        /// </summary>
        public static string CommandProvider_PromptSaveObject {
            get {
                return ResourceManager.GetString("CommandProvider_PromptSaveObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry number {0}. Ignoring Exception: {1}.
        /// </summary>
        public static string IgnoreOnException {
            get {
                return ResourceManager.GetString("IgnoreOnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The properties are not extensible..
        /// </summary>
        public static string Properties_NotExtensible {
            get {
                return ResourceManager.GetString("Properties_NotExtensible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove failed. Property {0} does not exist..
        /// </summary>
        public static string Remove_Failed_Property_NotFound {
            get {
                return ResourceManager.GetString("Remove_Failed_Property_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry number {0}. Delaying {1} ms before next retry. Exception: {2}.
        /// </summary>
        public static string RetryOnException {
            get {
                return ResourceManager.GetString("RetryOnException", resourceCulture);
            }
        }
    }
}
