//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackbirdSql.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AttributeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttributeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackbirdSql.Common.Properties.AttributeResources", typeof(AttributeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client library version..
        /// </summary>
        internal static string PropertyWindowClientVersionDescription {
            get {
                return ResourceManager.GetString("PropertyWindowClientVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client version.
        /// </summary>
        internal static string PropertyWindowClientVersionDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowClientVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string PropertyWindowConnection {
            get {
                return ResourceManager.GetString("PropertyWindowConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Details.
        /// </summary>
        internal static string PropertyWindowConnectionDetails {
            get {
                return ResourceManager.GetString("PropertyWindowConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the connection containing server name and login.
        /// </summary>
        internal static string PropertyWindowConnInfoDescription {
            get {
                return ResourceManager.GetString("PropertyWindowConnInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection name.
        /// </summary>
        internal static string PropertyWindowConnInfoDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowConnInfoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current connection parameters.
        /// </summary>
        internal static string PropertyWindowCurrentConnectionParameters {
            get {
                return ResourceManager.GetString("PropertyWindowCurrentConnectionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database path of the database for the connection.
        /// </summary>
        internal static string PropertyWindowDatabaseDescription {
            get {
                return ResourceManager.GetString("PropertyWindowDatabaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Path.
        /// </summary>
        internal static string PropertyWindowDatabaseDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowDatabaseDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of time it took for the command to execute and process result from the server.
        /// </summary>
        internal static string PropertyWindowElapsedTimeDescription {
            get {
                return ResourceManager.GetString("PropertyWindowElapsedTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        internal static string PropertyWindowElapsedTimeDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowElapsedTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time when the last result was returned.
        /// </summary>
        internal static string PropertyWindowFinishTimeDescription {
            get {
                return ResourceManager.GetString("PropertyWindowFinishTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish time.
        /// </summary>
        internal static string PropertyWindowFinishTimeDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowFinishTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login name of the connection.
        /// </summary>
        internal static string PropertyWindowLoginNameDescription {
            get {
                return ResourceManager.GetString("PropertyWindowLoginNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name.
        /// </summary>
        internal static string PropertyWindowLoginNameDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowLoginNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display name of the connection.
        /// </summary>
        internal static string PropertyWindowNameDescription {
            get {
                return ResourceManager.GetString("PropertyWindowNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string PropertyWindowNameDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tcpip port utilized by the Firebird server.
        /// </summary>
        internal static string PropertyWindowPortDescription {
            get {
                return ResourceManager.GetString("PropertyWindowPortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Port.
        /// </summary>
        internal static string PropertyWindowPortDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowPortDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Execution Details.
        /// </summary>
        internal static string PropertyWindowQueryExecutionDetailsCategory {
            get {
                return ResourceManager.GetString("PropertyWindowQueryExecutionDetailsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current query window options.
        /// </summary>
        internal static string PropertyWindowQueryWindowOptions {
            get {
                return ResourceManager.GetString("PropertyWindowQueryWindowOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server name of the connection.
        /// </summary>
        internal static string PropertyWindowServerNameDescription {
            get {
                return ResourceManager.GetString("PropertyWindowServerNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string PropertyWindowServerNameDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowServerNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server version of the connection.
        /// </summary>
        internal static string PropertyWindowServerVersionDescription {
            get {
                return ResourceManager.GetString("PropertyWindowServerVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server version.
        /// </summary>
        internal static string PropertyWindowServerVersionDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowServerVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tracing ID for the current session (Microsoft Azure SQL Database only).
        /// </summary>
        internal static string PropertyWindowSessionIDDescription {
            get {
                return ResourceManager.GetString("PropertyWindowSessionIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Tracing ID.
        /// </summary>
        internal static string PropertyWindowSessionIDDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowSessionIDDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time when the command was started.
        /// </summary>
        internal static string PropertyWindowStartTimeDescription {
            get {
                return ResourceManager.GetString("PropertyWindowStartTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string PropertyWindowStartTimeDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowStartTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of the connection.
        /// </summary>
        internal static string PropertyWindowStateDescription {
            get {
                return ResourceManager.GetString("PropertyWindowStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string PropertyWindowStateDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowStateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string PropertyWindowStatusDescription {
            get {
                return ResourceManager.GetString("PropertyWindowStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string PropertyWindowStatusDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowStatusDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of rows that are returned from the server.
        /// </summary>
        internal static string PropertyWindowTotalRowsReturnedDescription {
            get {
                return ResourceManager.GetString("PropertyWindowTotalRowsReturnedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows returned.
        /// </summary>
        internal static string PropertyWindowTotalRowsReturnedDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowTotalRowsReturnedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string QeQueryOptionsText {
            get {
                return ResourceManager.GetString("QeQueryOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatisticsPanelArrowBlank {
            get {
                object obj = ResourceManager.GetObject("StatisticsPanelArrowBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatisticsPanelArrowDown {
            get {
                object obj = ResourceManager.GetObject("StatisticsPanelArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatisticsPanelArrowFlat {
            get {
                object obj = ResourceManager.GetObject("StatisticsPanelArrowFlat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatisticsPanelArrowUp {
            get {
                object obj = ResourceManager.GetObject("StatisticsPanelArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Statistics.
        /// </summary>
        internal static string StatisticsPanelCategoryNetworkStats {
            get {
                return ResourceManager.GetString("StatisticsPanelCategoryNetworkStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Profile Statistics.
        /// </summary>
        internal static string StatisticsPanelCategoryQueryProfileStats {
            get {
                return ResourceManager.GetString("StatisticsPanelCategoryQueryProfileStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Statistics.
        /// </summary>
        internal static string StatisticsPanelCategoryServerStats {
            get {
                return ResourceManager.GetString("StatisticsPanelCategoryServerStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot Timestamp.
        /// </summary>
        internal static string StatisticsPanelCategorySnapshotTimestamp {
            get {
                return ResourceManager.GetString("StatisticsPanelCategorySnapshotTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Statistics.
        /// </summary>
        internal static string StatisticsPanelCategoryTimeStats {
            get {
                return ResourceManager.GetString("StatisticsPanelCategoryTimeStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network packet size.
        /// </summary>
        internal static string StatisticsPanelPacketSize {
            get {
                return ResourceManager.GetString("StatisticsPanelPacketSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string StatisticsPanelSnapshotAverage {
            get {
                return ResourceManager.GetString("StatisticsPanelSnapshotAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial  {0}.
        /// </summary>
        internal static string StatisticsPanelSnapshotClientStatsTrial {
            get {
                return ResourceManager.GetString("StatisticsPanelSnapshotClientStatsTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active users.
        /// </summary>
        internal static string StatisticsPanelStatActiveUserCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatActiveUserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server allocation pages.
        /// </summary>
        internal static string StatisticsPanelStatAllocationPages {
            get {
                return ResourceManager.GetString("StatisticsPanelStatAllocationPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Read/Write buffers.
        /// </summary>
        internal static string StatisticsPanelStatBufferCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatBufferCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDS packets sent from client.
        /// </summary>
        internal static string StatisticsPanelStatBuffersSent {
            get {
                return ResourceManager.GetString("StatisticsPanelStatBuffersSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current client memory allocation.
        /// </summary>
        internal static string StatisticsPanelStatCurrentMemory {
            get {
                return ResourceManager.GetString("StatisticsPanelStatCurrentMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database pages.
        /// </summary>
        internal static string StatisticsPanelStatDatabaseSizeInPages {
            get {
                return ResourceManager.GetString("StatisticsPanelStatDatabaseSizeInPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows affected by DELETE statements.
        /// </summary>
        internal static string StatisticsPanelStatDelRowCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatDelRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end time.
        /// </summary>
        internal static string StatisticsPanelStatExecutionEndTimeEpoch {
            get {
                return ResourceManager.GetString("StatisticsPanelStatExecutionEndTimeEpoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start time.
        /// </summary>
        internal static string StatisticsPanelStatExecutionStartTimeEpoch {
            get {
                return ResourceManager.GetString("StatisticsPanelStatExecutionStartTimeEpoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution time.
        /// </summary>
        internal static string StatisticsPanelStatExecutionTimeTicks {
            get {
                return ResourceManager.GetString("StatisticsPanelStatExecutionTimeTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of server expunge requests.
        /// </summary>
        internal static string StatisticsPanelStatExpungeCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatExpungeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows affected by INS, DEL, or UPD statements.
        /// </summary>
        internal static string StatisticsPanelStatIduRowCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatIduRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows affected by INSERT statements.
        /// </summary>
        internal static string StatisticsPanelStatInsRowCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatInsRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of server marks.
        /// </summary>
        internal static string StatisticsPanelStatMarks {
            get {
                return ResourceManager.GetString("StatisticsPanelStatMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum client memory allocated.
        /// </summary>
        internal static string StatisticsPanelStatMaxMemory {
            get {
                return ResourceManager.GetString("StatisticsPanelStatMaxMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time on server replies.
        /// </summary>
        internal static string StatisticsPanelStatNetworkServerTime {
            get {
                return ResourceManager.GetString("StatisticsPanelStatNetworkServerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet size.
        /// </summary>
        internal static string StatisticsPanelStatPacketSize {
            get {
                return ResourceManager.GetString("StatisticsPanelStatPacketSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database page size.
        /// </summary>
        internal static string StatisticsPanelStatPageSize {
            get {
                return ResourceManager.GetString("StatisticsPanelStatPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of server purge requests.
        /// </summary>
        internal static string StatisticsPanelStatPurgeCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatPurgeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of server read requests.
        /// </summary>
        internal static string StatisticsPanelStatReadCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatReadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server index read requests.
        /// </summary>
        internal static string StatisticsPanelStatReadIdxCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatReadIdxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server sequential read requests.
        /// </summary>
        internal static string StatisticsPanelStatReadSeqCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatReadSeqCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows returned by SELECT statements.
        /// </summary>
        internal static string StatisticsPanelStatSelectRowCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatSelectRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of server roundtrips.
        /// </summary>
        internal static string StatisticsPanelStatServerRoundtrips {
            get {
                return ResourceManager.GetString("StatisticsPanelStatServerRoundtrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of transactions .
        /// </summary>
        internal static string StatisticsPanelStatTransactions {
            get {
                return ResourceManager.GetString("StatisticsPanelStatTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows affected by UPDATE statements.
        /// </summary>
        internal static string StatisticsPanelStatUpdRowCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatUpdRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of server write requests.
        /// </summary>
        internal static string StatisticsPanelStatWriteCount {
            get {
                return ResourceManager.GetString("StatisticsPanelStatWriteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select type of time display to include on the status bar..
        /// </summary>
        internal static string ToolOptionExecutionTimeDescription {
            get {
                return ResourceManager.GetString("ToolOptionExecutionTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Execution Time.
        /// </summary>
        internal static string ToolOptionExecutionTimeDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionExecutionTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ToolOptionGeneralCategory {
            get {
                return ResourceManager.GetString("ToolOptionGeneralCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include database name.
        /// </summary>
        internal static string ToolOptionIncludeDBNameDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionIncludeDBNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include file name.
        /// </summary>
        internal static string ToolOptionIncludeFileNameDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionIncludeFileNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include login name.
        /// </summary>
        internal static string ToolOptionIncludeLoginNameDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionIncludeLoginNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include row count.
        /// </summary>
        internal static string ToolOptionIncludeRowCountDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionIncludeRowCountDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include server name.
        /// </summary>
        internal static string ToolOptionIncludeServerNameDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionIncludeServerNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt to save unsaved SQL query windows on close..
        /// </summary>
        internal static string ToolOptionPromptToSaveDescription {
            get {
                return ResourceManager.GetString("ToolOptionPromptToSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt to save.
        /// </summary>
        internal static string ToolOptionPromptToSaveDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionPromptToSaveDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed.
        /// </summary>
        internal static string ToolOptionShowTimeOptionElapsed {
            get {
                return ResourceManager.GetString("ToolOptionShowTimeOptionElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string ToolOptionShowTimeOptionEnd {
            get {
                return ResourceManager.GetString("ToolOptionShowTimeOptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ToolOptionShowTimeOptionNone {
            get {
                return ResourceManager.GetString("ToolOptionShowTimeOptionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar Content.
        /// </summary>
        internal static string ToolOptionStatusBarCategory {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar Color.
        /// </summary>
        internal static string ToolOptionStatusBarColorCategory {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background color of the status bar for single server connections.
        /// </summary>
        internal static string ToolOptionStatusBarDefaultColorDescription {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarDefaultColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string ToolOptionStatusBarDefaultColorDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarDefaultColorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the database name on the status bar..
        /// </summary>
        internal static string ToolOptionStatusBarIncludeDBNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarIncludeDBNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include login name on the status bar..
        /// </summary>
        internal static string ToolOptionStatusBarIncludeLoginNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarIncludeLoginNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include count of returned rows on the status bar..
        /// </summary>
        internal static string ToolOptionStatusBarIncludeRowCountDescription {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarIncludeRowCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include server name on the status bar..
        /// </summary>
        internal static string ToolOptionStatusBarIncludeServerNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarIncludeServerNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Text.
        /// </summary>
        internal static string ToolOptionTabTextCategory {
            get {
                return ResourceManager.GetString("ToolOptionTabTextCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the name of the current connected database in the tab text..
        /// </summary>
        internal static string ToolOptionTabTextIncludeDatabaseNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionTabTextIncludeDatabaseNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the name of the script file in the tab text..
        /// </summary>
        internal static string ToolOptionTabTextIncludeFileNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionTabTextIncludeFileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the name of the login for the connection in the tab text..
        /// </summary>
        internal static string ToolOptionTabTextIncludeLoginNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionTabTextIncludeLoginNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the name of the connected server in the tab text..
        /// </summary>
        internal static string ToolOptionTabTextIncludeServerNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionTabTextIncludeServerNameDescription", resourceCulture);
            }
        }
    }
}
