//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackbirdSql.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackbirdSql.Common.Properties.ControlsResources", typeof(ControlsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Actual_Executionplan {
            get {
                object obj = ResourceManager.GetObject("Actual_Executionplan", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of
        ///{1} ({2}%).
        /// </summary>
        public static string ActualOfEstimated {
            get {
                return ResourceManager.GetString("ActualOfEstimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrowDown {
            get {
                object obj = ResourceManager.GetObject("arrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrowFlat {
            get {
                object obj = ResourceManager.GetObject("arrowFlat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrowUp {
            get {
                object obj = ResourceManager.GetObject("arrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scroll interval should be greater than zero..
        /// </summary>
        public static string AutoScrollMoreThanZero {
            get {
                return ResourceManager.GetString("AutoScrollMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Clones.
        /// </summary>
        public static string BothClones {
            get {
                return ResourceManager.GetString("BothClones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument: buffer size should be a positive number..
        /// </summary>
        public static string BufferSizeShouldBePositive {
            get {
                return ResourceManager.GetString("BufferSizeShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new reader cannot be added while storage is storing data..
        /// </summary>
        public static string CannotAddReaderWhenStoringData {
            get {
                return ResourceManager.GetString("CannotAddReaderWhenStoringData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot print empty grid..
        /// </summary>
        public static string CannotPrintEmptyGrid {
            get {
                return ResourceManager.GetString("CannotPrintEmptyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state of the header item that is merged with the one to its right cannot be specified..
        /// </summary>
        public static string CannotSetMergeItemState {
            get {
                return ResourceManager.GetString("CannotSetMergeItemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell height must be greater than zero..
        /// </summary>
        public static string CellHeightShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("CellHeightShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration: Clustered.
        /// </summary>
        public static string ClusteredMode {
            get {
                return ResourceManager.GetString("ClusteredMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column index must be greater than or equal to zero and less than the number of columns..
        /// </summary>
        public static string ColumnIndexShouldBeInRange {
            get {
                return ResourceManager.GetString("ColumnIndexShouldBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column # {0} is not of checkbox type..
        /// </summary>
        public static string ColumnIsNotCheckBox {
            get {
                return ResourceManager.GetString("ColumnIsNotCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of columns in the new reader does not match storage..
        /// </summary>
        public static string ColumnsCountDoesNotMatch {
            get {
                return ResourceManager.GetString("ColumnsCountDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column definitions do not match those in the storage..
        /// </summary>
        public static string ColumnsDoNotMatch {
            get {
                return ResourceManager.GetString("ColumnsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns With No Statistics.
        /// </summary>
        public static string ColumnsWithNoStatistics {
            get {
                return ResourceManager.GetString("ColumnsWithNoStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns with no statistics warning..
        /// </summary>
        public static string ColumnsWithNoStatisticsDescription {
            get {
                return ResourceManager.GetString("ColumnsWithNoStatisticsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column width should be greater than zero..
        /// </summary>
        public static string ColumnWidthShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ColumnWidthShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column width in pixels should be less than or equal to {0}..
        /// </summary>
        public static string ColumnWidthShouldBeLessThanMax {
            get {
                return ResourceManager.GetString("ColumnWidthShouldBeLessThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken.
        /// </summary>
        public static string ConnectionStateBroken {
            get {
                return ResourceManager.GetString("ConnectionStateBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closed.
        /// </summary>
        public static string ConnectionStateClosed {
            get {
                return ResourceManager.GetString("ConnectionStateClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connecting.
        /// </summary>
        public static string ConnectionStateConnecting {
            get {
                return ResourceManager.GetString("ConnectionStateConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string ConnectionStateDebugging {
            get {
                return ResourceManager.GetString("ConnectionStateDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing.
        /// </summary>
        public static string ConnectionStateExecuting {
            get {
                return ResourceManager.GetString("ConnectionStateExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching.
        /// </summary>
        public static string ConnectionStateFetching {
            get {
                return ResourceManager.GetString("ConnectionStateFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not connected.
        /// </summary>
        public static string ConnectionStateNotConnected {
            get {
                return ResourceManager.GetString("ConnectionStateNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ConnectionStateOpen {
            get {
                return ResourceManager.GetString("ConnectionStateOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost: {0} %.
        /// </summary>
        public static string CostFormat {
            get {
                return ResourceManager.GetString("CostFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecoverable error; current control is not IGridEmbeddedControl..
        /// </summary>
        public static string CurControlIsNotIGridEmbedded {
            get {
                return ResourceManager.GetString("CurControlIsNotIGridEmbedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use class derived from the grid control to implement custom columns..
        /// </summary>
        public static string DeriveToImplementCustomColumn {
            get {
                return ResourceManager.GetString("DeriveToImplementCustomColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap design {
            get {
                object obj = ResourceManager.GetObject("design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &apos;Optimize rendering for screens with different pixel densities&apos; has been disabled. Restart Visual Studio to take effect..
        /// </summary>
        public static string DpiAwarenessIssue_Fix_Result_Message {
            get {
                return ResourceManager.GetString("DpiAwarenessIssue_Fix_Result_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to disable it..
        /// </summary>
        public static string DpiAwarenessIssue_Infobar_ActionItem_Text {
            get {
                return ResourceManager.GetString("DpiAwarenessIssue_Infobar_ActionItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling screen optimization for different pixel densities can avoid Data Flow display issues. Please click &quot;{0}&quot; and restart Visual Studio to make it work.
        ///You can enable it again from Visual Studio Options -&gt; Environment-&gt;General -&gt; Optimize rendering for screens with different pixel densities..
        /// </summary>
        public static string DpiAwarenessIssue_Message_Format {
            get {
                return ResourceManager.GetString("DpiAwarenessIssue_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge.
        /// </summary>
        public static string Edge {
            get {
                return ResourceManager.GetString("Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} from {2} to {3}.
        /// </summary>
        public static string EdgeDisplayPropertiesLabel {
            get {
                return ResourceManager.GetString("EdgeDisplayPropertiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Query Text from Showplan XML (possibly truncated).
        /// </summary>
        public static string EditQueryText {
            get {
                return ResourceManager.GetString("EditQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Or Secondary Clones.
        /// </summary>
        public static string EitherClones {
            get {
                return ResourceManager.GetString("EitherClones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set up page..
        /// </summary>
        public static string ErrUnableToPageSetup {
            get {
                return ResourceManager.GetString("ErrUnableToPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print results..
        /// </summary>
        public static string ErrUnableToPrintResults {
            get {
                return ResourceManager.GetString("ErrUnableToPrintResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Clone Match.
        /// </summary>
        public static string ExactMatchClones {
            get {
                return ResourceManager.GetString("ExactMatchClones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExecutionPlan {
            get {
                object obj = ResourceManager.GetObject("ExecutionPlan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Plan Description.
        /// </summary>
        public static string ExecutionPlanDescriptionAAName {
            get {
                return ResourceManager.GetString("ExecutionPlanDescriptionAAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Plan Graph.
        /// </summary>
        public static string ExecutionPlanGraphAAName {
            get {
                return ResourceManager.GetString("ExecutionPlanGraphAAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get temporary file name..
        /// </summary>
        public static string FailedToGetTempFileName {
            get {
                return ResourceManager.GetString("FailedToGetTempFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading execution plan XML file {0}..
        /// </summary>
        public static string FailedToLoadExecutionPlanFile {
            get {
                return ResourceManager.GetString("FailedToLoadExecutionPlanFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon FileEncodingDialog {
            get {
                object obj = ResourceManager.GetObject("FileEncodingDialog", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid calling sequence: file stream already initialized..
        /// </summary>
        public static string FileStreamAlreadyInitialized {
            get {
                return ResourceManager.GetString("FileStreamAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid calling sequence: file stream must be initialized first..
        /// </summary>
        public static string FileStreamNeedsToBeInitializedFirst {
            get {
                return ResourceManager.GetString("FileStreamNeedsToBeInitializedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First scrollable column index should be greater than or equal to zero and less than the number of columns..
        /// </summary>
        public static string FirstScrollableColumnShouldBeValid {
            get {
                return ResourceManager.GetString("FirstScrollableColumnShouldBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First scrollable row index should be greater than or equal to zero and less than the number of rows..
        /// </summary>
        public static string FirstScrollableRowShouldBeValid {
            get {
                return ResourceManager.GetString("FirstScrollableRowShouldBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first scrollable index will not be valid after deletion..
        /// </summary>
        public static string FirstScrollableWillBeBad {
            get {
                return ResourceManager.GetString("FirstScrollableWillBeBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A partial update was converted to a full update because of an online index build.
        /// </summary>
        public static string FullUpdateForOnlineIndexBuild {
            get {
                return ResourceManager.GetString("FullUpdateForOnlineIndexBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string GlobalizedLiteralFalse {
            get {
                return ResourceManager.GetString("GlobalizedLiteralFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string GlobalizedLiteralTrue {
            get {
                return ResourceManager.GetString("GlobalizedLiteralTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Enough Plan Found.
        /// </summary>
        public static string GoodEnoughPlanFound {
            get {
                return ResourceManager.GetString("GoodEnoughPlanFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridColumnInfoCollection is read-only, and its items cannot be modified..
        /// </summary>
        public static string GridColumnInfoCollectionIsReadOnly {
            get {
                return ResourceManager.GetString("GridColumnInfoCollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid column number should be greater than zero..
        /// </summary>
        public static string GridColumnNumberShouldBeAboveZero {
            get {
                return ResourceManager.GetString("GridColumnNumberShouldBeAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select all grid cells.
        /// </summary>
        public static string GridSelectAllCellsTooltip {
            get {
                return ResourceManager.GetString("GridSelectAllCellsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select the whole column.
        /// </summary>
        public static string GridSelectWholeColumnTooltip {
            get {
                return ResourceManager.GetString("GridSelectWholeColumnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select the whole row.
        /// </summary>
        public static string GridSelectWholeRowTooltip {
            get {
                return ResourceManager.GetString("GridSelectWholeRowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show in XML Editor
        ///      Click and hold to select this cell.
        /// </summary>
        public static string GridXMLCellTooltip {
            get {
                return ResourceManager.GetString("GridXMLCellTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash wrote {0} pages to and read {1} pages from tempdb with granted memory {2}KB and used memory {3}KB.
        /// </summary>
        public static string HashSpillDetails {
            get {
                return ResourceManager.GetString("HashSpillDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap horizontal_collapse {
            get {
                object obj = ResourceManager.GetObject("horizontal_collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap horizontal_expand {
            get {
                object obj = ResourceManager.GetObject("horizontal_expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hsplit {
            get {
                object obj = ResourceManager.GetObject("hsplit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditableCellType should be greater than or equal to EditableCellType.FirstCustomEditableCellType..
        /// </summary>
        public static string InvalidCellType {
            get {
                return ResourceManager.GetString("InvalidCellType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MergedHeaderResizeProportion property can be set only for columns that have merged header.
        /// </summary>
        public static string InvalidColIndexForMergedResizeProp {
            get {
                return ResourceManager.GetString("InvalidColIndexForMergedResizeProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create clipboard data object for currently selected block of cells because nothing is selected.
        /// </summary>
        public static string InvalidCurrentSelBlockForClicpboard {
            get {
                return ResourceManager.GetString("InvalidCurrentSelBlockForClicpboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom ColumnType should be greater than or equal to GridColumnType.FirstCustomColumnType..
        /// </summary>
        public static string InvalidCustomColType {
            get {
                return ResourceManager.GetString("InvalidCustomColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard operation cannot be performed in current grid state..
        /// </summary>
        public static string InvalidGridStateForClipboard {
            get {
                return ResourceManager.GetString("InvalidGridStateForClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MergedHeaderResizeProportion property should be between 0f and 1f..
        /// </summary>
        public static string InvalidMergedHeaderResizeProportion {
            get {
                return ResourceManager.GetString("InvalidMergedHeaderResizeProportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmbeddedComboBox.SetCurSelectionIndex: invalid index..
        /// </summary>
        public static string InvalidSelIndexInEmbeddedCombo {
            get {
                return ResourceManager.GetString("InvalidSelIndexInEmbeddedCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmbeddedComboBox.SetCurSelectionAsString: item that must be selected does not exist..
        /// </summary>
        public static string InvalidSelStringInEmbeddedCombo {
            get {
                return ResourceManager.GetString("InvalidSelStringInEmbeddedCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method should be called from the UI thread where the grid was created..
        /// </summary>
        public static string InvalidThreadForMethod {
            get {
                return ResourceManager.GetString("InvalidThreadForMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last non-scrollable column cannot have merged header..
        /// </summary>
        public static string LastNonScrollCannotBeMerged {
            get {
                return ResourceManager.GetString("LastNonScrollCannotBeMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query memory grant detected &quot;{0}&quot;, which may impact the reliability. Grant size: Initial {1} KB, Final {2} KB, Used {3} KB..
        /// </summary>
        public static string MemoryGrantWarning {
            get {
                return ResourceManager.GetString("MemoryGrantWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details on memory grant warning.
        /// </summary>
        public static string MemoryGrantWarningDescription {
            get {
                return ResourceManager.GetString("MemoryGrantWarningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Limit Exceeded.
        /// </summary>
        public static string MemoryLimitExceeded {
            get {
                return ResourceManager.GetString("MemoryLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server.
        /// </summary>
        public static string MessageBoxCaption {
            get {
                return ResourceManager.GetString("MessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Messages {
            get {
                object obj = ResourceManager.GetObject("Messages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipanel grid container is not available..
        /// </summary>
        public static string MultiPanelGridContainerIsNotAvailable {
            get {
                return ResourceManager.GetString("MultiPanelGridContainerIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string NameValuePair {
            get {
                return ResourceManager.GetString("NameValuePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        public static string NodeDisplayPropertiesName1 {
            get {
                return ResourceManager.GetString("NodeDisplayPropertiesName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}[{1}].
        /// </summary>
        public static string NodeDisplayPropertiesName2 {
            get {
                return ResourceManager.GetString("NodeDisplayPropertiesName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to embeddedControl must implement IGridEmbeddedControl..
        /// </summary>
        public static string NoIGridEmbeddedControl {
            get {
                return ResourceManager.GetString("NoIGridEmbeddedControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to embeddedControl MUST implement IGridEmbeddedControlManagement.
        /// </summary>
        public static string NoIGridEmbeddedControlManagement {
            get {
                return ResourceManager.GetString("NoIGridEmbeddedControlManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Join Predicate.
        /// </summary>
        public static string NoJoinPredicate {
            get {
                return ResourceManager.GetString("NoJoinPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Join predicate warning..
        /// </summary>
        public static string NoJoinPredicateDescription {
            get {
                return ResourceManager.GetString("NoJoinPredicateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set multiple selection blocks while in single selection mode..
        /// </summary>
        public static string NoMultiBlockSelInSingleSelMode {
            get {
                return ResourceManager.GetString("NoMultiBlockSelInSingleSelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot select non-existing cell ({0}, {1}, {2}, {3})..
        /// </summary>
        public static string NonExistingGridSelectionBlock {
            get {
                return ResourceManager.GetString("NonExistingGridSelectionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rows should be greater than or equal to zero..
        /// </summary>
        public static string NumOfRowsShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("NumOfRowsShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string ObjectAlias {
            get {
                return ResourceManager.GetString("ObjectAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias used for the referenced object..
        /// </summary>
        public static string ObjectAliasDescription {
            get {
                return ResourceManager.GetString("ObjectAliasDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string ObjectSchema {
            get {
                return ResourceManager.GetString("ObjectSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema name for the referenced object..
        /// </summary>
        public static string ObjectSchemaDescription {
            get {
                return ResourceManager.GetString("ObjectSchemaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ObjectServer {
            get {
                return ResourceManager.GetString("ObjectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string ObjectTable {
            get {
                return ResourceManager.GetString("ObjectTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name for the referenced object..
        /// </summary>
        public static string ObjectTableDescription {
            get {
                return ResourceManager.GetString("ObjectTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only SolidBrush can be specified as parameter.
        /// </summary>
        public static string OnlySolidBrush {
            get {
                return ResourceManager.GetString("OnlySolidBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#######} ({1}%).
        /// </summary>
        public static string OperatorDisplayCost {
            get {
                return ResourceManager.GetString("OperatorDisplayCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        public static string Parenthesis {
            get {
                return ResourceManager.GetString("Parenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per-thread counter information..
        /// </summary>
        public static string PerThreadCounterDescription {
            get {
                return ResourceManager.GetString("PerThreadCounterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type conversion in expression ({0}) may affect &quot;{1}&quot; in query plan choice.
        /// </summary>
        public static string PlanAffectingConvert {
            get {
                return ResourceManager.GetString("PlanAffectingConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan-affecting type conversion warning..
        /// </summary>
        public static string PlanAffectingConvertDescription {
            get {
                return ResourceManager.GetString("PlanAffectingConvertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Clones.
        /// </summary>
        public static string PrimaryClones {
            get {
                return ResourceManager.GetString("PrimaryClones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Properties_16x {
            get {
                object obj = ResourceManager.GetObject("Properties_16x", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string PropertyWindowConnection {
            get {
                return ResourceManager.GetString("PropertyWindowConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Details.
        /// </summary>
        public static string PropertyWindowConnectionDetails {
            get {
                return ResourceManager.GetString("PropertyWindowConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  ({1}).
        /// </summary>
        public static string PropertyWindowConnectionInfo {
            get {
                return ResourceManager.GetString("PropertyWindowConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the connection containing server name and login.
        /// </summary>
        public static string PropertyWindowConnInfoDescription {
            get {
                return ResourceManager.GetString("PropertyWindowConnInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection name.
        /// </summary>
        public static string PropertyWindowConnInfoDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowConnInfoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current connection parameters.
        /// </summary>
        public static string PropertyWindowCurrentConnectionParameters {
            get {
                return ResourceManager.GetString("PropertyWindowCurrentConnectionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database path of the database for the connection.
        /// </summary>
        public static string PropertyWindowDatabaseDescription {
            get {
                return ResourceManager.GetString("PropertyWindowDatabaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Path.
        /// </summary>
        public static string PropertyWindowDatabaseDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowDatabaseDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of time it took for the command to execute and process result from the server.
        /// </summary>
        public static string PropertyWindowElapsedTimeDescription {
            get {
                return ResourceManager.GetString("PropertyWindowElapsedTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        public static string PropertyWindowElapsedTimeDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowElapsedTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time when the last result was returned.
        /// </summary>
        public static string PropertyWindowFinishTimeDescription {
            get {
                return ResourceManager.GetString("PropertyWindowFinishTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish time.
        /// </summary>
        public static string PropertyWindowFinishTimeDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowFinishTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login name of the connection.
        /// </summary>
        public static string PropertyWindowLoginNameDescription {
            get {
                return ResourceManager.GetString("PropertyWindowLoginNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name.
        /// </summary>
        public static string PropertyWindowLoginNameDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowLoginNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display name of the connection.
        /// </summary>
        public static string PropertyWindowNameDescription {
            get {
                return ResourceManager.GetString("PropertyWindowNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string PropertyWindowNameDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tcpip port utilized by the Firebird server.
        /// </summary>
        public static string PropertyWindowPortDescription {
            get {
                return ResourceManager.GetString("PropertyWindowPortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Port.
        /// </summary>
        public static string PropertyWindowPortDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowPortDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Execution Details.
        /// </summary>
        public static string PropertyWindowQueryExecutionDetailsCategory {
            get {
                return ResourceManager.GetString("PropertyWindowQueryExecutionDetailsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current query window options.
        /// </summary>
        public static string PropertyWindowQueryWindowOptions {
            get {
                return ResourceManager.GetString("PropertyWindowQueryWindowOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server name of the connection.
        /// </summary>
        public static string PropertyWindowServerNameDescription {
            get {
                return ResourceManager.GetString("PropertyWindowServerNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        public static string PropertyWindowServerNameDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowServerNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server version of the connection.
        /// </summary>
        public static string PropertyWindowServerVersionDescription {
            get {
                return ResourceManager.GetString("PropertyWindowServerVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server version.
        /// </summary>
        public static string PropertyWindowServerVersionDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowServerVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tracing ID for the current session (Microsoft Azure SQL Database only).
        /// </summary>
        public static string PropertyWindowSessionIDDescription {
            get {
                return ResourceManager.GetString("PropertyWindowSessionIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Tracing ID.
        /// </summary>
        public static string PropertyWindowSessionIDDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowSessionIDDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time when the command was started.
        /// </summary>
        public static string PropertyWindowStartTimeDescription {
            get {
                return ResourceManager.GetString("PropertyWindowStartTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string PropertyWindowStartTimeDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowStartTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of the connection.
        /// </summary>
        public static string PropertyWindowStateDescription {
            get {
                return ResourceManager.GetString("PropertyWindowStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string PropertyWindowStateDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowStateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PropertyWindowStatusDescription {
            get {
                return ResourceManager.GetString("PropertyWindowStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PropertyWindowStatusDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowStatusDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of rows that are returned from the server.
        /// </summary>
        public static string PropertyWindowTotalRowsReturnedDescription {
            get {
                return ResourceManager.GetString("PropertyWindowTotalRowsReturnedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows returned.
        /// </summary>
        public static string PropertyWindowTotalRowsReturnedDisplayName {
            get {
                return ResourceManager.GetString("PropertyWindowTotalRowsReturnedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string QeQueryOptionsAdvanced {
            get {
                return ResourceManager.GetString("QeQueryOptionsAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSI.
        /// </summary>
        public static string QeQueryOptionsAnsi {
            get {
                return ResourceManager.GetString("QeQueryOptionsAnsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution.
        /// </summary>
        public static string QeQueryOptionsExecution {
            get {
                return ResourceManager.GetString("QeQueryOptionsExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string QeQueryOptionsGeneral {
            get {
                return ResourceManager.GetString("QeQueryOptionsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string QeQueryOptionsGrid {
            get {
                return ResourceManager.GetString("QeQueryOptionsGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string QeQueryOptionsResults {
            get {
                return ResourceManager.GetString("QeQueryOptionsResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string QeQueryOptionsText {
            get {
                return ResourceManager.GetString("QeQueryOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query {0}: Query cost (relative to the batch): {1}%.
        /// </summary>
        public static string QueryCostFormat {
            get {
                return ResourceManager.GetString("QueryCostFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string QueryWindowDisconnected {
            get {
                return ResourceManager.GetString("QueryWindowDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument: reader cannot be null..
        /// </summary>
        public static string ReaderCannotBeNull {
            get {
                return ResourceManager.GetString("ReaderCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Results {
            get {
                object obj = ResourceManager.GetObject("Results", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row index must be greater than or equal to zero and less than the number of rows..
        /// </summary>
        public static string RowIndexShouldBeInRange {
            get {
                return ResourceManager.GetString("RowIndexShouldBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread {0}.
        /// </summary>
        public static string RuntimeCounterThread {
            get {
                return ResourceManager.GetString("RuntimeCounterThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All threads.
        /// </summary>
        public static string RuntimeCounterThreadAll {
            get {
                return ResourceManager.GetString("RuntimeCounterThreadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread {0} on Instance {1}.
        /// </summary>
        public static string RuntimeCounterThreadOnInstance {
            get {
                return ResourceManager.GetString("RuntimeCounterThreadOnInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar Operator.
        /// </summary>
        public static string ScalarOperator {
            get {
                return ResourceManager.GetString("ScalarOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter should be greater than or equal to zero..
        /// </summary>
        public static string ScrollPosShouldBeMoreOrEqualZero {
            get {
                return ResourceManager.GetString("ScrollPosShouldBeMoreOrEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Clones.
        /// </summary>
        public static string SecondaryClones {
            get {
                return ResourceManager.GetString("SecondaryClones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek Keys.
        /// </summary>
        public static string SeekKeys {
            get {
                return ResourceManager.GetString("SeekKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys used by a seek operation..
        /// </summary>
        public static string SeekKeysDescription {
            get {
                return ResourceManager.GetString("SeekKeysDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}.{2} {3}).
        /// </summary>
        public static string ServerNameAndBuildAndProduct {
            get {
                return ResourceManager.GetString("ServerNameAndBuildAndProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text and bitmap for the header item that is merged with the one to its right cannot be specified..
        /// </summary>
        public static string ShouldBeNoDataForMergedColumHeader {
            get {
                return ResourceManager.GetString("ShouldBeNoDataForMergedColumHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to column # {0} has check box on its header. Use overloaded HeaderInfo method for such columns..
        /// </summary>
        public static string ShouldSetHeaderStateForCheckBox {
            get {
                return ResourceManager.GetString("ShouldSetHeaderStateForCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to column # {0} does not have check box on its header. Use overloaded HeaderInfo method for such columns..
        /// </summary>
        public static string ShouldSetHeaderStateForRegualrCol {
            get {
                return ResourceManager.GetString("ShouldSetHeaderStateForRegualrCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort wrote {0} pages to and read {1} pages from tempdb with granted memory {2}KB and used memory {3}KB.
        /// </summary>
        public static string SortSpillDetails {
            get {
                return ResourceManager.GetString("SortSpillDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortView default constructor cannot be used..
        /// </summary>
        public static string SortViewDefaultConstructorCannotBeUsed {
            get {
                return ResourceManager.GetString("SortViewDefaultConstructorCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator used tempdb to spill data during execution.
        /// </summary>
        public static string SpillOccurredDisplayString {
            get {
                return ResourceManager.GetString("SpillOccurredDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator used tempdb to spill data during execution with spill level {0} and {1} spilled thread(s).
        /// </summary>
        public static string SpillToTempDb {
            get {
                return ResourceManager.GetString("SpillToTempDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator used tempdb to spill data during execution with spill level {0}.
        /// </summary>
        public static string SpillToTempDbOld {
            get {
                return ResourceManager.GetString("SpillToTempDbOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button1.
        /// </summary>
        public static string SplitViewContainer_DefaultButton1Text {
            get {
                return ResourceManager.GetString("SplitViewContainer_DefaultButton1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button2.
        /// </summary>
        public static string SplitViewContainer_DefaultButton2Text {
            get {
                return ResourceManager.GetString("SplitViewContainer_DefaultButton2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string SplitViewContainer_DefaultButtonText {
            get {
                return ResourceManager.GetString("SplitViewContainer_DefaultButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sql {
            get {
                object obj = ResourceManager.GetObject("sql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution visualizer (Actual).
        /// </summary>
        public static string SqlEditorTabbedEditorPane_ActualPlan_Button_Text {
            get {
                return ResourceManager.GetString("SqlEditorTabbedEditorPane_ActualPlan_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution plan (Actual).
        /// </summary>
        public static string SqlEditorTabbedEditorPane_ActualTextPlan_Button_Text {
            get {
                return ResourceManager.GetString("SqlEditorTabbedEditorPane_ActualTextPlan_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string SqlEditorTabbedEditorPane_Message_Button_Text {
            get {
                return ResourceManager.GetString("SqlEditorTabbedEditorPane_Message_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution visualizer (Estimated).
        /// </summary>
        public static string SqlEditorTabbedEditorPane_Plan_Button_Text {
            get {
                return ResourceManager.GetString("SqlEditorTabbedEditorPane_Plan_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string SqlEditorTabbedEditorPane_Results_Button_Text {
            get {
                return ResourceManager.GetString("SqlEditorTabbedEditorPane_Results_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FB-SQL.
        /// </summary>
        public static string SqlEditorTabbedEditorPane_Sql_Button_Text {
            get {
                return ResourceManager.GetString("SqlEditorTabbedEditorPane_Sql_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string SqlEditorTabbedEditorPane_Statistics_Button_Text {
            get {
                return ResourceManager.GetString("SqlEditorTabbedEditorPane_Statistics_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution plan (Estimated).
        /// </summary>
        public static string SqlEditorTabbedEditorPane_TextPlan_Button_Text {
            get {
                return ResourceManager.GetString("SqlEditorTabbedEditorPane_TextPlan_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Expression Predicate.
        /// </summary>
        public static string StartupExpressionPredicate {
            get {
                return ResourceManager.GetString("StartupExpressionPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Statistics {
            get {
                object obj = ResourceManager.GetObject("Statistics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_cancel {
            get {
                object obj = ResourceManager.GetObject("StatusBar_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_connect {
            get {
                object obj = ResourceManager.GetObject("StatusBar_connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_error {
            get {
                object obj = ResourceManager.GetObject("StatusBar_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_offline {
            get {
                object obj = ResourceManager.GetObject("StatusBar_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin1 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin10 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin11 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin12 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin13 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin14 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin2 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin3 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin4 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin5 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin6 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin7 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin8 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_spin9 {
            get {
                object obj = ResourceManager.GetObject("StatusBar_spin9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusBar_success {
            get {
                object obj = ResourceManager.GetObject("StatusBar_success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status bar.
        /// </summary>
        public static string StatusBarAccessibleName {
            get {
                return ResourceManager.GetString("StatusBarAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling query....
        /// </summary>
        public static string StatusBarCancellingQuery {
            get {
                return ResourceManager.GetString("StatusBarCancellingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        public static string StatusBarConnected {
            get {
                return ResourceManager.GetString("StatusBarConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting..
        /// </summary>
        public static string StatusBarConnecting {
            get {
                return ResourceManager.GetString("StatusBarConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Ready.
        /// </summary>
        public static string StatusBarConnectionReady {
            get {
                return ResourceManager.GetString("StatusBarConnectionReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging query....
        /// </summary>
        public static string StatusBarDebuggingQuery {
            get {
                return ResourceManager.GetString("StatusBarDebuggingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected..
        /// </summary>
        public static string StatusBarDisconnected {
            get {
                return ResourceManager.GetString("StatusBarDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing query....
        /// </summary>
        public static string StatusBarExecutingQuery {
            get {
                return ResourceManager.GetString("StatusBarExecutingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection Opened.
        /// </summary>
        public static string StatusBarNewConnectionOpened {
            get {
                return ResourceManager.GetString("StatusBarNewConnectionOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rows.
        /// </summary>
        public static string StatusBarNumberOfReturnedRows {
            get {
                return ResourceManager.GetString("StatusBarNumberOfReturnedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing query batch....
        /// </summary>
        public static string StatusBarParsingQueryBatch {
            get {
                return ResourceManager.GetString("StatusBarParsingQueryBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query canceled..
        /// </summary>
        public static string StatusBarQueryCanceled {
            get {
                return ResourceManager.GetString("StatusBarQueryCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query executed successfully at {0:T}.
        /// </summary>
        public static string StatusBarQueryCompletedSuccessfully {
            get {
                return ResourceManager.GetString("StatusBarQueryCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query completed with errors..
        /// </summary>
        public static string StatusBarQueryCompletedWithErrors {
            get {
                return ResourceManager.GetString("StatusBarQueryCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query batch timed out..
        /// </summary>
        public static string StatusBarQueryTimedOut {
            get {
                return ResourceManager.GetString("StatusBarQueryTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid calling sequence: storage must be initialized first..
        /// </summary>
        public static string StorageNotInitialized {
            get {
                return ResourceManager.GetString("StorageNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swap_horz {
            get {
                object obj = ResourceManager.GetObject("swap_horz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swap_vert {
            get {
                object obj = ResourceManager.GetObject("swap_vert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Pane.
        /// </summary>
        public static string TabbedEditor_CollapsePane {
            get {
                return ResourceManager.GetString("TabbedEditor_CollapsePane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Split.
        /// </summary>
        public static string TabbedEditor_HorizontalSplit {
            get {
                return ResourceManager.GetString("TabbedEditor_HorizontalSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string TabbedEditor_SplitContainerButton1Text {
            get {
                return ResourceManager.GetString("TabbedEditor_SplitContainerButton1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string TabbedEditor_SplitContainerButton2Text {
            get {
                return ResourceManager.GetString("TabbedEditor_SplitContainerButton2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Strip.
        /// </summary>
        public static string TabbedEditor_SplitStrip {
            get {
                return ResourceManager.GetString("TabbedEditor_SplitStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string TabbedEditor_SwapButton {
            get {
                return ResourceManager.GetString("TabbedEditor_SwapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Split.
        /// </summary>
        public static string TabbedEditor_VerticalSplit {
            get {
                return ResourceManager.GetString("TabbedEditor_VerticalSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TextPlan {
            get {
                object obj = ResourceManager.GetObject("TextPlan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        public static string ToolBarHostAccessibleName {
            get {
                return ResourceManager.GetString("ToolBarHostAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select type of time display to include on the status bar..
        /// </summary>
        public static string ToolOptionExecutionTimeDescription {
            get {
                return ResourceManager.GetString("ToolOptionExecutionTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Execution Time.
        /// </summary>
        public static string ToolOptionExecutionTimeDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionExecutionTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ToolOptionGeneralCategory {
            get {
                return ResourceManager.GetString("ToolOptionGeneralCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include database name.
        /// </summary>
        public static string ToolOptionIncludeDBNameDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionIncludeDBNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include file name.
        /// </summary>
        public static string ToolOptionIncludeFileNameDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionIncludeFileNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include login name.
        /// </summary>
        public static string ToolOptionIncludeLoginNameDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionIncludeLoginNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include row count.
        /// </summary>
        public static string ToolOptionIncludeRowCountDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionIncludeRowCountDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include server name.
        /// </summary>
        public static string ToolOptionIncludeServerNameDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionIncludeServerNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt to save unsaved SQL query windows on close..
        /// </summary>
        public static string ToolOptionPromptToSaveDescription {
            get {
                return ResourceManager.GetString("ToolOptionPromptToSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt to save.
        /// </summary>
        public static string ToolOptionPromptToSaveDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionPromptToSaveDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed.
        /// </summary>
        public static string ToolOptionShowTimeOptionElapsed {
            get {
                return ResourceManager.GetString("ToolOptionShowTimeOptionElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string ToolOptionShowTimeOptionEnd {
            get {
                return ResourceManager.GetString("ToolOptionShowTimeOptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ToolOptionShowTimeOptionNone {
            get {
                return ResourceManager.GetString("ToolOptionShowTimeOptionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar Content.
        /// </summary>
        public static string ToolOptionStatusBarCategory {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar Color.
        /// </summary>
        public static string ToolOptionStatusBarColorCategory {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background color of the status bar for single server connections.
        /// </summary>
        public static string ToolOptionStatusBarDefaultColorDescription {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarDefaultColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string ToolOptionStatusBarDefaultColorDisplayName {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarDefaultColorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the database name on the status bar..
        /// </summary>
        public static string ToolOptionStatusBarIncludeDBNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarIncludeDBNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include login name on the status bar..
        /// </summary>
        public static string ToolOptionStatusBarIncludeLoginNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarIncludeLoginNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include count of returned rows on the status bar..
        /// </summary>
        public static string ToolOptionStatusBarIncludeRowCountDescription {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarIncludeRowCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include server name on the status bar..
        /// </summary>
        public static string ToolOptionStatusBarIncludeServerNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionStatusBarIncludeServerNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Text.
        /// </summary>
        public static string ToolOptionTabTextCategory {
            get {
                return ResourceManager.GetString("ToolOptionTabTextCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the name of the current connected database in the tab text..
        /// </summary>
        public static string ToolOptionTabTextIncludeDatabaseNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionTabTextIncludeDatabaseNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the name of the script file in the tab text..
        /// </summary>
        public static string ToolOptionTabTextIncludeFileNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionTabTextIncludeFileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the name of the login for the connection in the tab text..
        /// </summary>
        public static string ToolOptionTabTextIncludeLoginNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionTabTextIncludeLoginNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the name of the connected server in the tab text..
        /// </summary>
        public static string ToolOptionTabTextIncludeServerNameDescription {
            get {
                return ResourceManager.GetString("ToolOptionTabTextIncludeServerNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TSQL {
            get {
                object obj = ResourceManager.GetObject("TSQL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected run type..
        /// </summary>
        public static string UnexpectedRunType {
            get {
                return ResourceManager.GetString("UnexpectedRunType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution plan source type can not be recognized..
        /// </summary>
        public static string UnknownExecutionPlanSource {
            get {
                return ResourceManager.GetString("UnknownExecutionPlanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vertical_collapse {
            get {
                object obj = ResourceManager.GetObject("vertical_collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vertical_expand {
            get {
                object obj = ResourceManager.GetObject("vertical_expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vsplit {
            get {
                object obj = ResourceManager.GetObject("vsplit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query had to wait {0} seconds for {1} during execution.
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom level must be an integer value between {0} and {1}..
        /// </summary>
        public static string ZoomLevelShouldBeBetween {
            get {
                return ResourceManager.GetString("ZoomLevelShouldBeBetween", resourceCulture);
            }
        }
    }
}
