//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdmxTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIEntities : DbContext
    {
        public SIEntities()
            : base("name=SIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SH_CONSIGNMENTTYPE> SH_CONSIGNMENTTYPE { get; set; }
        public virtual DbSet<SH_DOCUMENT> SH_DOCUMENT { get; set; }
    }
}
