//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackbirdSql.VisualStudio.Ddex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AttributeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttributeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackbirdSql.VisualStudio.Ddex.Properties.AttributeResources", typeof(AttributeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string OptionCategoryDebugging {
            get {
                return ResourceManager.GetString("OptionCategoryDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string OptionCategoryDiagnostics {
            get {
                return ResourceManager.GetString("OptionCategoryDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityFramework settings.
        /// </summary>
        public static string OptionCategoryEntityFramework {
            get {
                return ResourceManager.GetString("OptionCategoryEntityFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  General.
        /// </summary>
        public static string OptionCategoryGeneral {
            get {
                return ResourceManager.GetString("OptionCategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query designer.
        /// </summary>
        public static string OptionCategoryQueryDesigner {
            get {
                return ResourceManager.GetString("OptionCategoryQueryDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the execution of Diagnostics calls. This option should remain enabled. Disabling does not disable Exceptions..
        /// </summary>
        public static string OptionDescriptionEnableDiagnostics {
            get {
                return ResourceManager.GetString("OptionDescriptionEnableDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables diagnostics logging to a log file..
        /// </summary>
        public static string OptionDescriptionEnableDiagnosticsLog {
            get {
                return ResourceManager.GetString("OptionDescriptionEnableDiagnosticsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the execution of Firebird Debug.Dug()/Debug.Trace() calls. Only applicable to builds that include the debug Firebird library..
        /// </summary>
        public static string OptionDescriptionEnableFbDiagnostics {
            get {
                return ResourceManager.GetString("OptionDescriptionEnableFbDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables logging of tasks to the output window pane. This option should remain enabled..
        /// </summary>
        public static string OptionDescriptionEnableTaskLog {
            get {
                return ResourceManager.GetString("OptionDescriptionEnableTaskLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the execution of Diag.Trace() calls..
        /// </summary>
        public static string OptionDescriptionEnableTrace {
            get {
                return ResourceManager.GetString("OptionDescriptionEnableTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Sql Tracer output to be directed to Diag.Trace()..
        /// </summary>
        public static string OptionDescriptionEnableTracer {
            get {
                return ResourceManager.GetString("OptionDescriptionEnableTracer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of Firebird diagnostics log file. Note: Only applicable to builds that include the debug Firerbird library..
        /// </summary>
        public static string OptionDescriptionFbLogFile {
            get {
                return ResourceManager.GetString("OptionDescriptionFbLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, includes any configured connection strings that exist in a solution&apos;s projects in the drop down selection lists when adding a new connection..
        /// </summary>
        public static string OptionDescriptionIncludeAppConnections {
            get {
                return ResourceManager.GetString("OptionDescriptionIncludeAppConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of diagnostics log file..
        /// </summary>
        public static string OptionDescriptionLogFile {
            get {
                return ResourceManager.GetString("OptionDescriptionLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables persistent validation flags. If disabled the validation flag of solutions and projects will be repeated upon reopening if Validation is enabled. Only applicable to DEBUG builds..
        /// </summary>
        public static string OptionDescriptionPersistentValidation {
            get {
                return ResourceManager.GetString("OptionDescriptionPersistentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the extrapolated IVsDataObjectSupport xml (TObjectSupport.xml), after imports, to the directory location of the diagnostics log file..
        /// </summary>
        public static string OptionDescriptionSaveExtrapolatedXml {
            get {
                return ResourceManager.GetString("OptionDescriptionSaveExtrapolatedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the query designer diagram pane to visible when a table or view&apos;s data is initially retrieved..
        /// </summary>
        public static string OptionDescriptionShowDiagramPane {
            get {
                return ResourceManager.GetString("OptionDescriptionShowDiagramPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this option to allow BlackbirdSql to ensure that Firebird EntityFramework is configured in your non-CPS projects&apos; App.config..
        /// </summary>
        public static string OptionDescriptionValidateConfig {
            get {
                return ResourceManager.GetString("OptionDescriptionValidateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this option to allow BlackbirdSql to update legacy edmx models to use EntityFramework 6..
        /// </summary>
        public static string OptionDescriptionValidateEdmx {
            get {
                return ResourceManager.GetString("OptionDescriptionValidateEdmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder to be used for the Firebird diagnostics log file..
        /// </summary>
        public static string OptionDialogFbLogFile {
            get {
                return ResourceManager.GetString("OptionDialogFbLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files(*.*)|*.*.
        /// </summary>
        public static string OptionDialogFilterFbLogFile {
            get {
                return ResourceManager.GetString("OptionDialogFilterFbLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files(*.*)|*.*.
        /// </summary>
        public static string OptionDialogFilterLogFile {
            get {
                return ResourceManager.GetString("OptionDialogFilterLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder to be used for the diagnostics log file..
        /// </summary>
        public static string OptionDialogLogFile {
            get {
                return ResourceManager.GetString("OptionDialogLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable diagnostics.
        /// </summary>
        public static string OptionDisplayEnableDiagnostics {
            get {
                return ResourceManager.GetString("OptionDisplayEnableDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable diagnostics logging.
        /// </summary>
        public static string OptionDisplayEnableDiagnosticsLog {
            get {
                return ResourceManager.GetString("OptionDisplayEnableDiagnosticsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Firebird diagnostics.
        /// </summary>
        public static string OptionDisplayEnableFbDiagnostics {
            get {
                return ResourceManager.GetString("OptionDisplayEnableFbDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save extrapolated xml.
        /// </summary>
        public static string OptionDisplayEnableSaveExtrapolatedXml {
            get {
                return ResourceManager.GetString("OptionDisplayEnableSaveExtrapolatedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable task logging.
        /// </summary>
        public static string OptionDisplayEnableTaskLog {
            get {
                return ResourceManager.GetString("OptionDisplayEnableTaskLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable trace.
        /// </summary>
        public static string OptionDisplayEnableTrace {
            get {
                return ResourceManager.GetString("OptionDisplayEnableTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tracer.
        /// </summary>
        public static string OptionDisplayEnableTracer {
            get {
                return ResourceManager.GetString("OptionDisplayEnableTracer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebird Log file.
        /// </summary>
        public static string OptionDisplayFbLogFile {
            get {
                return ResourceManager.GetString("OptionDisplayFbLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include solution connections.
        /// </summary>
        public static string OptionDisplayIncludeAppConnections {
            get {
                return ResourceManager.GetString("OptionDisplayIncludeAppConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file.
        /// </summary>
        public static string OptionDisplayLogFile {
            get {
                return ResourceManager.GetString("OptionDisplayLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent validation flags.
        /// </summary>
        public static string OptionDisplayPersistentValidation {
            get {
                return ResourceManager.GetString("OptionDisplayPersistentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial state of Diagram Pane.
        /// </summary>
        public static string OptionDisplayShowDiagramPane {
            get {
                return ResourceManager.GetString("OptionDisplayShowDiagramPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate App.config.
        /// </summary>
        public static string OptionDisplayValidateConfig {
            get {
                return ResourceManager.GetString("OptionDisplayValidateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update legacy edmx models.
        /// </summary>
        public static string OptionDisplayValidateEdmx {
            get {
                return ResourceManager.GetString("OptionDisplayValidateEdmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackbirdSql DDEX 2.0.
        /// </summary>
        public static string OptionPageCategory {
            get {
                return ResourceManager.GetString("OptionPageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string OptionPageNameDebug {
            get {
                return ResourceManager.GetString("OptionPageNameDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionPageNameGeneral {
            get {
                return ResourceManager.GetString("OptionPageNameGeneral", resourceCulture);
            }
        }
    }
}
