//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackbirdSql.VisualStudio.Ddex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackbirdSql.VisualStudio.Ddex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments array is invalid..
        /// </summary>
        public static string DataSupportObject_InvalidInvokeArguments {
            get {
                return ResourceManager.GetString("DataSupportObject_InvalidInvokeArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method name is unknown..
        /// </summary>
        public static string DataSupportObject_UnknownInvokeName {
            get {
                return ResourceManager.GetString("DataSupportObject_UnknownInvokeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this selection to connect to Firebird using the DDEX 2.0 BlackbirdSql Provider.
        /// </summary>
        public static string DdexProvider_Description {
            get {
                return ResourceManager.GetString("DdexProvider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework DDEX 2.0 Provider for Firebird (BlackbirdSql).
        /// </summary>
        public static string DdexProvider_DisplayName {
            get {
                return ResourceManager.GetString("DdexProvider_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackbirdSql DDEX 2.0 Provider.
        /// </summary>
        public static string DdexProvider_ShortDisplayName {
            get {
                return ResourceManager.GetString("DdexProvider_ShortDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters array contains invalid elements..
        /// </summary>
        public static string DSRefBuilder_InvalidParameters {
            get {
                return ResourceManager.GetString("DSRefBuilder_InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection site is required to build a DSRef..
        /// </summary>
        public static string DSRefBuilder_MissingSite {
            get {
                return ResourceManager.GetString("DSRefBuilder_MissingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add a null site.
        /// </summary>
        public static string ExceptionAddingNullSite {
            get {
                return ResourceManager.GetString("ExceptionAddingNullSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add a null connection.
        /// </summary>
        public static string ExceptionAttemptToAddNullConnection {
            get {
                return ResourceManager.GetString("ExceptionAttemptToAddNullConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to exit a synchronous state when the object was not in a synchronous state.
        /// </summary>
        public static string ExceptionAttemptToExitSyncFromAsync {
            get {
                return ResourceManager.GetString("ExceptionAttemptToExitSyncFromAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} class assembly not found.
        /// </summary>
        public static string ExceptionClassAssemblyNotFound {
            get {
                return ResourceManager.GetString("ExceptionClassAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata collection {0} is not supported..
        /// </summary>
        public static string ExceptionCollectionNotSupported {
            get {
                return ResourceManager.GetString("ExceptionCollectionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection closed.
        /// </summary>
        public static string ExceptionConnectionClosed {
            get {
                return ResourceManager.GetString("ExceptionConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection disposed.
        /// </summary>
        public static string ExceptionConnectionDisposed {
            get {
                return ResourceManager.GetString("ExceptionConnectionDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is null.
        /// </summary>
        public static string ExceptionConnectionNull {
            get {
                return ResourceManager.GetString("ExceptionConnectionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTE is null.
        /// </summary>
        public static string ExceptionDteIsNull {
            get {
                return ResourceManager.GetString("ExceptionDteIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source information for site already exists.
        /// </summary>
        public static string ExceptionDuplicatingSiteInformation {
            get {
                return ResourceManager.GetString("ExceptionDuplicatingSiteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events already enabled.
        /// </summary>
        public static string ExceptionEventsAlreadyEnabled {
            get {
                return ResourceManager.GetString("ExceptionEventsAlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve Package settings.
        /// </summary>
        public static string ExceptionFailedToRetrievePackageSettings {
            get {
                return ResourceManager.GetString("ExceptionFailedToRetrievePackageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to subscribe to Option events.
        /// </summary>
        public static string ExceptionFailedToSubscribeOptionEvents {
            get {
                return ResourceManager.GetString("ExceptionFailedToSubscribeOptionEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBPackageController is null.
        /// </summary>
        public static string ExceptionIBPackageControllerIsNull {
            get {
                return ResourceManager.GetString("ExceptionIBPackageControllerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon resource invalid: {0}..
        /// </summary>
        public static string ExceptionIconResourceInvalid {
            get {
                return ResourceManager.GetString("ExceptionIconResourceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon resource not found: {0}..
        /// </summary>
        public static string ExceptionIconResourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionIconResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import resource not found: {0}..
        /// </summary>
        public static string ExceptionImportResourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionImportResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters are invalid.
        /// </summary>
        public static string ExceptionInvalidParameters {
            get {
                return ResourceManager.GetString("ExceptionInvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata collection {0} is pre-built and may not be called from here..
        /// </summary>
        public static string ExceptionInvalidPrebuiltMetadataCall {
            get {
                return ResourceManager.GetString("ExceptionInvalidPrebuiltMetadataCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The raw metadata collection {0} may not be called from here..
        /// </summary>
        public static string ExceptionInvalidRawMetadataCall {
            get {
                return ResourceManager.GetString("ExceptionInvalidRawMetadataCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVsRunningDocumentTable is null.
        /// </summary>
        public static string ExceptionIVsRunningDocumentTableIsNull {
            get {
                return ResourceManager.GetString("ExceptionIVsRunningDocumentTableIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate Describer for connection parameter &apos;{0}&apos;..
        /// </summary>
        public static string ExceptionParameterDescriberNotFound {
            get {
                return ResourceManager.GetString("ExceptionParameterDescriberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found: {0}.
        /// </summary>
        public static string ExceptionResourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of provided specifications [{0}] is not equal to the specified restrictions [{1}]..
        /// </summary>
        public static string ExceptionRestrictionsNotEqualToSpecified {
            get {
                return ResourceManager.GetString("ExceptionRestrictionsNotEqualToSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site is null.
        /// </summary>
        public static string ExceptionSiteIsNull {
            get {
                return ResourceManager.GetString("ExceptionSiteIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVsSolution is null.
        /// </summary>
        public static string ExceptionSVsSolutionIsNull {
            get {
                return ResourceManager.GetString("ExceptionSVsSolutionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTokenSource was found to be null when exiting sync.
        /// </summary>
        public static string ExceptionSyncTokenSourceNull {
            get {
                return ResourceManager.GetString("ExceptionSyncTokenSourceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Error at Column index: {0}..
        /// </summary>
        public static string ExceptionTriggerErrorAtColumnIndex {
            get {
                return ResourceManager.GetString("ExceptionTriggerErrorAtColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at Trigger column index: {0}, Generator column index: {1}..
        /// </summary>
        public static string ExceptionTriggerGeneratorErrorAtColumnIndex {
            get {
                return ResourceManager.GetString("ExceptionTriggerGeneratorErrorAtColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported population mechanism: {0}.
        /// </summary>
        public static string ExceptionUnsupportedPopulationMechanism {
            get {
                return ResourceManager.GetString("ExceptionUnsupportedPopulationMechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;  Cancelled. {0}% completed. {1} took {2}ms..
        /// </summary>
        public static string LinkageParserCancelled {
            get {
                return ResourceManager.GetString("LinkageParserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;  Cancelled {0} sequence linkage..
        /// </summary>
        public static string LinkageParserCancelledCatalog {
            get {
                return ResourceManager.GetString("LinkageParserCancelledCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switched {0} sequence linkage to UI thread..
        /// </summary>
        public static string LinkageParserCatalogSwitchedToUiThread {
            get {
                return ResourceManager.GetString("LinkageParserCatalogSwitchedToUiThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% completed. {1}
        ///Linkage completed in {2}ms..
        /// </summary>
        public static string LinkageParserCompleted {
            get {
                return ResourceManager.GetString("LinkageParserCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed {0} sequence linkage in {1}ms..
        /// </summary>
        public static string LinkageParserCompletedCatalog {
            get {
                return ResourceManager.GetString("LinkageParserCompletedCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;  Pausing async sequence linkage..
        /// </summary>
        public static string LinkageParserPausingAsync {
            get {
                return ResourceManager.GetString("LinkageParserPausingAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% completed. {1}.
        /// </summary>
        public static string LinkageParserPercentCompletedStage {
            get {
                return ResourceManager.GetString("LinkageParserPercentCompletedStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% completed. {1} took {2}ms..
        /// </summary>
        public static string LinkageParserPercentCompletedStageElapsed {
            get {
                return ResourceManager.GetString("LinkageParserPercentCompletedStageElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;  Resuming async sequence linkage..
        /// </summary>
        public static string LinkageParserResumingAsync {
            get {
                return ResourceManager.GetString("LinkageParserResumingAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming {0} sequence linkage..
        /// </summary>
        public static string LinkageParserResumingCatalog {
            get {
                return ResourceManager.GetString("LinkageParserResumingCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed and linked {0} Triggers..
        /// </summary>
        public static string LinkageParserStageCompleted {
            get {
                return ResourceManager.GetString("LinkageParserStageCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting Generators....
        /// </summary>
        public static string LinkageParserStageGeneratorsBegin {
            get {
                return ResourceManager.GetString("LinkageParserStageGeneratorsBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Generators.
        /// </summary>
        public static string LinkageParserStageGeneratorsEnd {
            get {
                return ResourceManager.GetString("LinkageParserStageGeneratorsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populating Linkage Table....
        /// </summary>
        public static string LinkageParserStageLinkingBegin {
            get {
                return ResourceManager.GetString("LinkageParserStageLinkingBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate Linkage Table.
        /// </summary>
        public static string LinkageParserStageLinkingEnd {
            get {
                return ResourceManager.GetString("LinkageParserStageLinkingEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populating Sequence Table....
        /// </summary>
        public static string LinkageParserStageSequencesBegin {
            get {
                return ResourceManager.GetString("LinkageParserStageSequencesBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate Sequence Table.
        /// </summary>
        public static string LinkageParserStageSequencesEnd {
            get {
                return ResourceManager.GetString("LinkageParserStageSequencesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TriggerDependencies.
        /// </summary>
        public static string LinkageParserStageTriggerDependenciesEnd {
            get {
                return ResourceManager.GetString("LinkageParserStageTriggerDependenciesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting TriggerDependencies....
        /// </summary>
        public static string LinkageParserStageTriggerDependenciesStart {
            get {
                return ResourceManager.GetString("LinkageParserStageTriggerDependenciesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting Triggers....
        /// </summary>
        public static string LinkageParserStageTriggersBegin {
            get {
                return ResourceManager.GetString("LinkageParserStageTriggersBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Triggers.
        /// </summary>
        public static string LinkageParserStageTriggersEnd {
            get {
                return ResourceManager.GetString("LinkageParserStageTriggersEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string LinkageParserStarted {
            get {
                return ResourceManager.GetString("LinkageParserStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;  Switched sequence linkage to UI thread..
        /// </summary>
        public static string LinkageParserSwitchedToUiThread {
            get {
                return ResourceManager.GetString("LinkageParserSwitchedToUiThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  sequence linkage.
        /// </summary>
        public static string LinkageParserTaskHandlerTitle {
            get {
                return ResourceManager.GetString("LinkageParserTaskHandlerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating sequence linkage..
        /// </summary>
        public static string LinkageParserUpdating {
            get {
                return ResourceManager.GetString("LinkageParserUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0} sequence linkage..
        /// </summary>
        public static string LinkageParserUpdatingCatalog {
            get {
                return ResourceManager.GetString("LinkageParserUpdatingCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Provider for Firebird (FirebirdClient).
        /// </summary>
        public static string Provider_DisplayName {
            get {
                return ResourceManager.GetString("Provider_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirebirdClient Provider.
        /// </summary>
        public static string Provider_ShortDisplayName {
            get {
                return ResourceManager.GetString("Provider_ShortDisplayName", resourceCulture);
            }
        }
    }
}
