//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackbirdSql.VisualStudio.Ddex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackbirdSql.VisualStudio.Ddex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackbirdSql .NET Framework DDEX 2.0 Provider for Firebird.
        /// </summary>
        public static string DataProvider_Ddex {
            get {
                return ResourceManager.GetString("DataProvider_Ddex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this selection to connect to Firebird using the DDEX 2.0 BlackbirdSql Provider..
        /// </summary>
        public static string DataProvider_Ddex_DataSource_Description {
            get {
                return ResourceManager.GetString("DataProvider_Ddex_DataSource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this data provider to connect to a Firebird database..
        /// </summary>
        public static string DataProvider_Ddex_Description {
            get {
                return ResourceManager.GetString("DataProvider_Ddex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirebirdClient [BlackbirdSql].
        /// </summary>
        public static string DataProvider_Ddex_Short {
            get {
                return ResourceManager.GetString("DataProvider_Ddex_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackbirdSql .NET Framework Data Provider for Firebird {0}.
        /// </summary>
        public static string DataProvider_Name {
            get {
                return ResourceManager.GetString("DataProvider_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebird Server.
        /// </summary>
        public static string DataSource_FirebirdServer {
            get {
                return ResourceManager.GetString("DataSource_FirebirdServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add a null site.
        /// </summary>
        public static string ExceptionAddingNullSite {
            get {
                return ResourceManager.GetString("ExceptionAddingNullSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to exit a synchronous state when the object was not in a synchronous state.
        /// </summary>
        public static string ExceptionAttemptToExitSyncFromAsync {
            get {
                return ResourceManager.GetString("ExceptionAttemptToExitSyncFromAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} class assembly not found.
        /// </summary>
        public static string ExceptionClassAssemblyNotFound {
            get {
                return ResourceManager.GetString("ExceptionClassAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata collection {0} is not supported..
        /// </summary>
        public static string ExceptionCollectionNotSupported {
            get {
                return ResourceManager.GetString("ExceptionCollectionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character set is not defined.
        ///
        ///If you are sure the character set exists and you are connecting to multiple versions of embedded databases then note that Firebird 4 and 5 embedded databases cannot be accessed during the same session as Firebird  2 and 3 embedded databases.
        ///To access this database you will need to restart your Visual Studio session.
        ///
        ///The database engine returned the following message at {0}:
        ///{1}.
        /// </summary>
        public static string ExceptionDbCharacterSet {
            get {
                return ResourceManager.GetString("ExceptionDbCharacterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Set not Defined.
        /// </summary>
        public static string ExceptionDbCharacterSetCaption {
            get {
                return ResourceManager.GetString("ExceptionDbCharacterSetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect database client active for this database. 
        ///
        ///If you are connecting to an embedded database, then for Firebird version 2 set the &apos;ClientLibrary&apos; to &apos;fbembed&apos;, for version 3 to &apos;fbclient&apos;, and for versions 4 and 5 to &apos;fbembed45\fbclient&apos;.
        ///
        ///The database engine returned the following message at {0}:
        ///{1}.
        /// </summary>
        public static string ExceptionDbVersionMismatch {
            get {
                return ResourceManager.GetString("ExceptionDbVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Version Mismatch.
        /// </summary>
        public static string ExceptionDbVersionMismatchCaption {
            get {
                return ResourceManager.GetString("ExceptionDbVersionMismatchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source information for site already exists.
        /// </summary>
        public static string ExceptionDuplicatingSiteInformation {
            get {
                return ResourceManager.GetString("ExceptionDuplicatingSiteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve Package settings.
        /// </summary>
        public static string ExceptionFailedToRetrievePackageSettings {
            get {
                return ResourceManager.GetString("ExceptionFailedToRetrievePackageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to subscribe to Settings events.
        /// </summary>
        public static string ExceptionFailedToSubscribeSettingsEvents {
            get {
                return ResourceManager.GetString("ExceptionFailedToSubscribeSettingsEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon resource invalid: {0}..
        /// </summary>
        public static string ExceptionIconResourceInvalid {
            get {
                return ResourceManager.GetString("ExceptionIconResourceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon resource not found: {0}..
        /// </summary>
        public static string ExceptionIconResourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionIconResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import resource not found: {0}..
        /// </summary>
        public static string ExceptionImportResourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionImportResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters are invalid.
        /// </summary>
        public static string ExceptionInvalidParameters {
            get {
                return ResourceManager.GetString("ExceptionInvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata collection {0} is pre-built and may not be called from here..
        /// </summary>
        public static string ExceptionInvalidPrebuiltMetadataCall {
            get {
                return ResourceManager.GetString("ExceptionInvalidPrebuiltMetadataCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The raw metadata collection {0} may not be called from here..
        /// </summary>
        public static string ExceptionInvalidRawMetadataCall {
            get {
                return ResourceManager.GetString("ExceptionInvalidRawMetadataCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Firebird client plugin.
        ///
        ///If you are connecting to multiple versions of embedded databases then note that Firebird 4 and 5 embedded databases cannot be accessed during the same session as Firebird  2 and 3 embedded databases.
        ///To access this database you will need to restart your Visual Studio session.
        ///
        ///The database engine returned the following message at {0}:
        ///{1}.
        /// </summary>
        public static string ExceptionLoadingPlugin {
            get {
                return ResourceManager.GetString("ExceptionLoadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Firebird Client Plugin.
        /// </summary>
        public static string ExceptionLoadingPluginCaption {
            get {
                return ResourceManager.GetString("ExceptionLoadingPluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found: {0}.
        /// </summary>
        public static string ExceptionResourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of provided specifications [{0}] is not equal to the specified restrictions [{1}]..
        /// </summary>
        public static string ExceptionRestrictionsNotEqualToSpecified {
            get {
                return ResourceManager.GetString("ExceptionRestrictionsNotEqualToSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site is null.
        /// </summary>
        public static string ExceptionSiteIsNull {
            get {
                return ResourceManager.GetString("ExceptionSiteIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTokenSource was found to be null when exiting sync.
        /// </summary>
        public static string ExceptionSyncTokenSourceNull {
            get {
                return ResourceManager.GetString("ExceptionSyncTokenSourceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported population mechanism: {0}.
        /// </summary>
        public static string ExceptionUnsupportedPopulationMechanism {
            get {
                return ResourceManager.GetString("ExceptionUnsupportedPopulationMechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IVsDataConnectionProperties property: {0}..
        /// </summary>
        public static string IVsDataConnectionProperties_PropertyInvalid {
            get {
                return ResourceManager.GetString("IVsDataConnectionProperties_PropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database path: {0}..
        /// </summary>
        public static string LabelDatabasePath {
            get {
                return ResourceManager.GetString("LabelDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Provider for Firebird (FirebirdClient).
        /// </summary>
        public static string Provider_DisplayName {
            get {
                return ResourceManager.GetString("Provider_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirebirdClient Provider.
        /// </summary>
        public static string Provider_ShortDisplayName {
            get {
                return ResourceManager.GetString("Provider_ShortDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query{1}: DesignData{0}.
        /// </summary>
        public static string QueryDesignerDocument_NewQueryCaption {
            get {
                return ResourceManager.GetString("QueryDesignerDocument_NewQueryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}: DesignData{0}.
        /// </summary>
        public static string QueryDesignerDocument_RetrieveDataCaption {
            get {
                return ResourceManager.GetString("QueryDesignerDocument_RetrieveDataCaption", resourceCulture);
            }
        }
    }
}
